### ISSUE TITLE
 Support for spaCy models

### ISSUE THREAD

**Issue by katarkor** [QData/TextAttack#117]
Hi,
I was asked by @jxmorris12 to create this issue in connection to my original question on Stackoverflow: 
https://stackoverflow.com/questions/61889477/using-spacy-models-with-allennlp-interpret-or-textattack/61897642?noredirect=1#comment109982631_61897642

I tried to figure out how to use **Textattack** with spaCy models, but was unsuccessful. I'll be grateful for any help :)

**Comment by katarkor** [comment]
Thank you :) 
I have one base model that I trained with spaCy's train function (https://spacy.io/api/cli#train) on an entity-free version of this treebank: https://github.com/ltgoslo/norne/tree/master/ud/nob with tagger and parser in the pipeline (no NER) and some word vectors (let me know if you need details on that). Then I trained several models for different tasks on top of that: NER, sentiment analysis and text classification. The sentiment analysis one was trained using this script https://github.com/explosion/spaCy/blob/master/examples/training/train_textcat.py, but I changed the input data to this treebank https://github.com/ltgoslo/norec with film reviews and assigned them positive/negative labels based on the 1-6 score from the treebank. For NER and text classification I used Prodigy (https://prodi.gy/, by the same guys who created spaCy), because I wanted to annotate my own data and then I used Prodigy's train function (https://prodi.gy/docs/recipes#training). Unfortunately Prodigy's code is not open source, but it's 100% compatible with spaCy (I actually trained my Spacy-trained sentiment analysis model further with Prodigy to get better results).

**Comment by jxmorris12** [comment]
Hi @katarkor --

Just wanted to say that we haven't forgotten about your question and I'm sorry about the delay! We're going to overhaul the way we import models within the next month or so. This will make it much easier for you to use TextAttack with spacy!

Can you provide me some sample code that imports one of your models (either NER or text classification) and predicts a piece of text?

something like:
```
>> text = "I love this movie – it has such beautiful scenery!"
>> model = load_model_somehow()
>> print(model.predict(text)) 
[[0.997, 0.003]]
```

^ that's a totally made-up part of code, and `model.predict` doesn't have to exist. But if you can provide me with this sample code, I can show you how to write a wrapper file and use that file with TextAttack! :)

**Comment by katarkor** [comment]
Hi,
no worries :) For NER it works like this:
```
import spacy
# load the model
nlp = spacy.load("spacy_models/your_ner_model")
text = "I saw Hanne and Marie in Oslo today."
# here is where the magic happens
doc = nlp(text)
for token in doc:
    print(token.text, token.ent_type_)
```
This results in:
I
saw 
Hanne PER
and
Marie PER
in 
Oslo LOC
today 
. 

It only provides the most probable option for NER, I once tried to figure out how to get probabilities for all NER labels, but gave up, I think it was somewhere in the Cython part. For text classification on the other hand you get the probabilities:
```
nlp = spacy.load("spacy_models/your_textcat_model")
text = "This movie was bad."
doc = nlp(text)
print(doc.cats)
```
Then you get a dictionary with the scores, like:
{'POSITIVE': 0.0, 'NEUTRAL': 0.1, 'NEGATIVE': 0.9}

**Comment by jxmorris12** [comment]
Hi @katarkor -- thank you for being patient :)

Ok, so named entity recognition is something we're working on, and don't support yet. But model wrappers should make us compatible with spaCy now, so let's try sentiment analysis!

Here is some code for a model wrapper around the spaCy sentiment analysis model you showed above. Since most datasets only have two classes (positive and negative) I split the neutral part of each prediction between the positive and negative classes.

```
import numpy as np
from textattack.models.wrappers import ModelWrapper

class spaCySentimentAnalysisWrapper(ModelWrapper):
    def __init__(self, nlp):
        self.nlp = nlp
    def __call__(self, text_inputs):
        outputs = []
        for text in text_inputs:
          output = self.nlp(text)
          pos = output['POSITIVE'] + output['NEUTRAL']/2
          neg = output['NEGATIVE'] + output['NEUTRAL']/2
          outputs.append([neg, pos])
        return np.array(outputs)
```

And then here's some code for loading and attacking that model wrapper:

```
import spacy
import textattack
from textattack.attack_recipes import TextFoolerJin2019

nlp = spacy.load("spacy_models/your_textcat_model")
model_wrapper = spaCySentimentAnalysisWrapper(nlp)
recipe = TextFoolerJin2019.build(model_wrapper)

result = []

dataset = textattack.datasets.HuggingFaceNlpDataset('glue', 'sst2', 'validation')
for x in recipe.attack_dataset(dataset):
  result.append(x)
  print(x.__str__(color_method = 'ansi'))
```

I wasn't able to test this since I don't have access to a spaCy sentiment analysis model. Please do let me know if this (or something close to it) works for you!

**Comment by katarkor** [comment]
Hi, thanks a lot, I'll give it a try! 😃

**Comment by qiyanjun** [comment]
@katarkor is this solved?

**Comment by katarkor** [comment]
@qiyanjun hi, sorry for taking so long, I got busy with other things at work. I tried to run it, but I get this error:
AttributeError: module 'textattack.datasets' has no attribute 'HuggingFaceNlpDataset'
Which version should I use? I installed 0.2.11.

**Comment by jxmorris12** [comment]
@katarkor oh yeah, our API has changed a tiny bit! `HuggingFaceNlpDataset` is now `HuggingFaceDataset`. Change that and let us know how it goes!

**Comment by katarkor** [comment]
@jxmorris12 I got some errors, but I fixed it now:
```python
import numpy as np
from textattack.models.wrappers import ModelWrapper

class spaCySentimentAnalysisWrapper(ModelWrapper):
    def __init__(self, nlp):
        self.nlp = nlp
    def __call__(self, text_inputs):
        outputs = []
        for text in text_inputs:
            output = self.nlp(text)
            if 'NEUTRAL' in output.cats:
                pos = output.cats['POSITIVE'] + output.cats['NEUTRAL']/2
                neg = output.cats['NEGATIVE'] + output.cats['NEUTRAL']/2
            else:
                pos = output.cats['POSITIVE']
                neg = output.cats['NEGATIVE']
            outputs.append([neg, pos])
        return np.array(outputs)
```
The problem was the missing .cats on output (and I also added the check for neutral class in case the model only has positive and negative). So now it runs, but my model is for Norwegian and I get English text, how do I change that?

**Comment by jxmorris12** [comment]
Hmm ok we're close! What command are you running @katarkor? You probably have to supply a Norwegian dataset, I'm thinking.

**Comment by katarkor** [comment]
@jxmorris12 I'm running the exact same code you postet above, only I change "your_textcat_model" to an actual model name I have. I'm guessing I should make some changes to how I define "dataset", but how do I do that? What format of a dataset is supported?

**Comment by jxmorris12** [comment]
good question @katarkor!! That `HuggingFaceDataset` class loads datasets automatically from [this datasets package](https://github.com/huggingface/datasets). Instead, you should load the dataset yourself as a list of tuples where each tuple is a (text, label) pair. See this section of the readme: https://github.com/QData/TextAttack#dataset-from-a-file

**Comment by katarkor** [comment]
Ok, I'll check it out, thanks 😃

**Comment by jxmorris12** [comment]
@katarkor Awesome! ok if we close the issue for now?

**Comment by katarkor** [comment]
Yup, I think I'll figure it out now

**Comment by jxmorris12** [comment]
So glad! This has been a long time coming haha. Thanks!
