### ISSUE TITLE
Dataset class that can import data from local files should be provided

### ISSUE THREAD

**Issue by jind11** [QData/TextAttack#118]
hi, I suggest two things: 1). Provide dev set instead of train set in the current available datasets classes; 2). Provide a dataset class that can import data from local files so that users can deal with their own data. Thanks!

**Comment by jxmorris12** [comment]
Hi, these are great suggestions. Tonight we released version `0.0.3.0` which should make this easier. 

1. We'll get samples from the dev set up as quickly as possible for the provided datasets (Yelp, MR, IMDB, and SNLI). We just added support for huggingface NLP datasets which might help you too.
2. We don't support automatically reading from a text file or CSV, but you can write a quick wrapper for your dataset and import that using the new `--dataset-from-file` option. Datasets are iterables of `(input, output)` tuples. I whipped up a [Colab notebook](https://colab.research.google.com/drive/1FtYaK0kcjAA9Is-m27MuVTwadIdxZhM4?usp=sharing) that shows an example how to use this option. Does that help with the datasets issue?

**Comment by jind11** [comment]
I just now wrote a wrapper myself but this would require me to use this source code as a local package instead of installing it. However, in order to use this repository as a local package, I need to change the name of the folder "tokenizers" since it has the same name as another package which is for the "transformers".

**Comment by jxmorris12** [comment]
Hmm, that's a problem. Maybe we can fix this by renaming the `textattack` folder to `src/textattack`? I don't want to have to rename our packages...

**Comment by jind11** [comment]
I used this command so that I can resolve the dependency problems: export PYTHONPATH=$PYTHONPATH:‘pwd‘. In this way, you do not need to change the package name, but just need to change the folder name "tokenizers" to something else, such as "tokenizer",

**Comment by jxmorris12** [comment]
Ok, so two problems to fix here:

1. Loading dataset from file works, but it's not trivial. We should add some helpers and examples to make this easier for people. Even better, --load-dataset-from-csv could be a very nice feature.

2. Using `tokenizers` as a module name was fine until we started importing the [`tokenizers`](https://github.com/huggingface/tokenizers) package. Now, this is a mess. Need to rename or find a workaround.

**Comment by marwanomar1** [comment]
Hello, I am doing adv training for a model but I get the following error:
import textattack
import transformers
!pip install datasets
import datasets
from datasets import load_dataset

model = transformers.AutoModelForSequenceClassification.from_pretrained("bert-base-uncased")
tokenizer = transformers.AutoTokenizer.from_pretrained("bert-base-uncased")
model_wrapper = textattack.models.wrappers.HuggingFaceModelWrapper(model, tokenizer)

# We only use DeepWordBugGao2018 to demonstration purposes.
attack = textattack.attack_recipes.DeepWordBugGao2018.build(model_wrapper)
train_dataset = load_dataset('squad', split='train')
eval_dataset = load_dataset('squad', split='validation')

# Train for 3 epochs with 1 initial clean epochs, 1000 adversarial examples per epoch, learning rate of 5e-5, and effective batch size of 32 (8x4).
training_args = textattack.TrainingArgs(
    num_epochs=3,
    num_clean_epochs=1,
    num_train_adv_examples=1000,
    learning_rate=5e-5,
    per_device_train_batch_size=8,
    gradient_accumulation_steps=4,
    log_to_tb=True,
)

trainer = textattack.Trainer(
    model_wrapper,
    "classification",
    attack,
   
    eval_dataset,
    training_args
)
trainer.train()



AssertionError: `train_dataset` must be of type `textattack.datasets.Dataset`, but got type `<class 'datasets.arrow_dataset.Dataset'>`.

**Comment by marwanomar1** [comment]
Can someone please help me with this errror.

**Comment by jxmorris12** [comment]
Thanks for the comment @marwanomar1 - can you post this as a new issue please? You commented on an old issue, which isn't really relevant. 

But a quick diagnosis tells me you should be using our `HuggingFaceDataset` class to wrap the dataset instead of just importing it directly from huggingface datasets.  so in the code you posted, your dataset initializations might look something like:

```python
from textattack.datasets import HuggingFaceDataset

train_dataset = HuggingFaceDataset('squad', split='train')
eval_dataset = HuggingFaceDataset('squad', split='validation')
```

you can tag me (@jxmorris12) when you post a new issue and I'll try and help you there.

**Comment by marwanomar1** [comment]
Thank you, Jack! I just posted this as a new issue and tagged you on it.

Thank you for your help in-advance.
