### ISSUE TITLE
Files automatically cached in home folder

### ISSUE THREAD

**Issue by jxmorris12** [QData/TextAttack#119]
TextAttack automatically downloads files to `~/.cache/`, which isn't ideal for every user. We should ask for the best cache_dir on the `_post_install_hook` and use that, instead of just defaulting to `~/.cache/`.

**Comment by jxmorris12** [comment]
There are other cache directories (besides `TA_CACHE_DIR`) that need to be specified via env variables to
- `TFHUB_CACHE_DIR`
- `PYTORCH_TRANSFORMERS_CACHE` 
- the Google language modeling cache directory too

**Comment by jind11** [comment]
Should also set up the cache directory for the nlp package: HF_HOME

**Comment by jind11** [comment]
matplolib also has a cache directory, which can be set up by: MPLCONFIGDIR
