### ISSUE TITLE
Make some imports optional

### ISSUE THREAD

**Issue by jxmorris12** [QData/TextAttack#123]
I want to use TextAttack but I don't want to install `tensorflow` or `spacy`. I should be able to install TA without those modules and then be prompted to install them if I want to use the spacy tokenizer or tensorflow features.

**Comment by jxmorris12** [comment]
Turns out this is more complicated than I thought. Will come back around to this in the future if others request.

**Comment by tpatzelt** [comment]
Hello, 
I agree that this is not an easy issue and might require some structural changes. Do you think this will be implemented at some point? Having torch as hard requirement seems reasonable, but also requiring tensorflow and spacy no matter tokenizer or features are used makes it hard for me integrate TA into my current project. Thank you
