### ISSUE TITLE
Diagnose CPU vs. GPU precision issues

### ISSUE THREAD

**Issue by jxmorris12** [QData/TextAttack#177]
attacks on CPU and GPU produce different query numbers

attack on CPU: `CUDA_VISIBLE_DEVICES="" textattack attack --model lstm-mr --recipe faster-alzantot --num-examples 3 --num-examples-offset 20`

```
+-------------------------------+--------+
| Attack Results                |        |
+-------------------------------+--------+
| Number of successful attacks: | 2      |
| Number of failed attacks:     | 1      |
| Number of skipped attacks:    | 0      |
| Original accuracy:            | 100.0% |
| Accuracy under attack:        | 33.33% |
| Attack success rate:          | 66.67% |
| Average perturbed word %:     | 8.58%  |
| Average num. words per input: | 25.67  |
| Avg num queries:              | 878.33 |
+-------------------------------+--------+
```

attack on GPU: `CUDA_VISIBLE_DEVICES=0 textattack attack --model lstm-mr --recipe faster-alzantot --num-examples 3 --num-examples-offset 20`
```
+-------------------------------+--------+
| Attack Results                |        |
+-------------------------------+--------+
| Number of successful attacks: | 2      |
| Number of failed attacks:     | 1      |
| Number of skipped attacks:    | 0      |
| Original accuracy:            | 100.0% |
| Accuracy under attack:        | 33.33% |
| Attack success rate:          | 66.67% |
| Average perturbed word %:     | 8.58%  |
| Average num. words per input: | 25.67  |
| Avg num queries:              | 859.0  |
+-------------------------------+--------+
```

**Comment by donggrant** [comment]
![image](https://user-images.githubusercontent.com/48699101/141396054-7cd1990b-44b5-4f52-b270-00f4d58cf364.png)
^CPU Local^

![image](https://user-images.githubusercontent.com/48699101/141396071-76d49515-47cf-42b9-9530-d524226888cc.png)
^GPU Colab^

This seems to be a very old issue, but the command seems to give consistent number of queries now, so the problem is probably already fixed.

**Comment by jxmorris12** [comment]
Awesome, @donggrant - thanks for checking on this! I guess HuggingFace fixed their precision upstream.
