### ISSUE TITLE
Goal function should print maximization

### ISSUE THREAD

**Issue by jxmorris12** [QData/TextAttack#180]
the input reduction recipe prints the following:

```
Attack(
  (search_method): GreedyWordSwapWIR(
    (wir_method):  delete
  )
  (goal_function):  InputReduction(
    (target_num_words):  1
  )
  (transformation):  WordDeletion
  (constraints): 
    (0): RepeatModification
    (1): StopwordModification
  (is_black_box):  True
)
```

however, it should be clear from the print message that the `InputReduction` goal function is to be maximized (not achieved)

**Comment by uvafan** [comment]
It should also not print `target_num_words` if it's maximizable, since it doesn't have any effect when it's maximizable.
