### ISSUE TITLE
Add MORPHEUS as an attack

### ISSUE THREAD

**Issue by jxmorris12** [QData/TextAttack#181]
An attack that we haven't yet implemented but fits well in our framework is "It’s Morphin’ Time!
Combating Linguistic Discrimination with Inflectional Perturbations" [https://arxiv.org/pdf/2005.04364.pdf].

The search method is our `GreedyWordSwap` search. We need to add the transformation and goal function.

I think the attack can be implemented by adding the following:

1. **Transformation:** We can add the inflection-based transformation by adding `lemminflect` to requirements.txt and creating a transformation similarly to this portion of their code: https://github.com/salesforce/morpheus/blob/master/morpheus/morpheus_base.py

2. **Goal function:** the greedy goal of this attack is to minimize the BLEU score of the ground-truth and after-attack output of the model. We can add BLEU score as a text2text goal function with the following thresholds:
> Only adversarial examples that degraded the F1 score by 50 and the BLEU score by >15 were considered.

(Once we add a question-answering model & dataset, we can implement a goal function based on F1 score.)

Finally, we'd also need to add a recipe file that utilizes the transformation, goal function, and our GreedyWordSwap search. I don't think this attack has any constraints, though I may have missed them in the paper.

**Comment by samsontmr** [comment]
Morpheus also works for classification other than QA (here's the example for NLI: https://github.com/salesforce/morpheus/blob/master/morpheus/morpheus_nli.py). It should be compatible with the existing classification goal functions you have.

**Comment by jxmorris12** [comment]
Good call @samsontmr -- let's open another issue!
