### ISSUE TITLE
Use <details> for README

### ISSUE THREAD

**Issue by heytitle** [QData/TextAttack#188]
There is a HTML tag `<details>` that we can use inside Markdown. Browsers will automatically render the content of this black with a toggle block. So, I think it might be good to use it for the project's README because some parts are quite lengthly.

Please see my example at: https://github.com/heytitle/TextAttack/tree/patch-1#attacks-and-papers-implemented-attack-recipes

<img width="896" alt="image" src="https://user-images.githubusercontent.com/1214890/86601453-a1001b00-bfa1-11ea-8004-6445e8324d8b.png">

**Comment by jxmorris12** [comment]
good idea 👍

**Comment by qiyanjun** [comment]
@heytitle is the current Table of Recipes working? https://textattack.readthedocs.io/en/latest/1start/attacks4Components.html
