### ISSUE TITLE
GoogleLM's print_step isn't never specified anywhere

### ISSUE THREAD

**Issue by heytitle** [QData/TextAttack#197]
There is a debugging block in GoogleLM that relies on `print_step`, but it seems this attribute is never defined; hence, causing an error.

https://github.com/QData/TextAttack/blob/087880c586a5a123c2d5159df6b58e26807f1b00/textattack/constraints/grammaticality/language_models/google_language_model/google_language_model.py#L80

Can we simply remove the block?

**Comment by jxmorris12** [comment]
thanks @heytitle! this was fixed in #198
