### ISSUE TITLE
Better naming for CSVLogger

### ISSUE THREAD

**Issue by heytitle** [QData/TextAttack#201]
Currently, logging to CSV uses the following format `attack-[timestamp].csv`.  This might be a bit challenging to track results, e.g. it's not clear from the name that what method or recipe was used for the attack. 

Because several cmd arguments are already text or string, it might be a good idea to use them for constructing the filename. For example, something like
```
[model]-[recipe]-[timestamp]
```
`timestamp` could also be more readable using `yyyy-mm-dd--hh-ms`.

**Comment by uvafan** [comment]
There should also be an option for specifying the output filename in addition to its directory.
