### ISSUE TITLE
Multilanguage attack

### ISSUE THREAD

**Issue by lfdharo** [QData/TextAttack#215]
Hi, I'm surprised by the capabilities of this library and I would like to know if it can handle the generation or test attacks for other languages, e.g. Spanish, German, Japanese. In case it is currently not allowed, what would be your advise to overcome this issue.

Thanks

**Comment by jxmorris12** [comment]
Hi @lfdharo! This is something we've talked about and would love to add. TextAttack builds attacks from four modules: search method, transformation, goal function, and constraints. Generally, the search methods and goal functions are language-agnostic (although there are rare exceptions). The transformations and constraints, however, are generally based around English -- for example, swapping out words based on an English thesaurus, or constraining based on English part-of-speech.

I'd love to see transformations and constraints added for other languages. Spanish and German seem like they'd be more straightforward, but I am afraid Japanese might require some more refactoring behind-the-scenes.

That said, I think most common cases would be very easy to implement. There is nothing inherent to TextAttack that depends on any specific language. For example, something as simple as adding a Spanish thesaurus transformation would work just fine out-of-the-box!

Are you interested in working on adding components from other languages?

**Comment by heytitle** [comment]
@c4n would it be something that we can do for Thai?

**Comment by c4n** [comment]
@heytitle yes, depending on linguistics resources/licenses.

**Comment by FlorianO** [comment]
As i added Multilingual universal sentence encoder as a new constraint you should be able to use it as a constraint for thai.

**Comment by qiyanjun** [comment]
Please see https://github.com/QData/TextAttack/projects/2
