### ISSUE TITLE
FileNotFoundError: Tried to load model from path - could not find train_args.json.

### ISSUE THREAD

**Issue by swayson** [QData/TextAttack#224]
Hi, I used transformers 3.0.2 to train a masked language model and wanted to give `TextAttack` a try.
Bit confused by needing a `train_args.json` file, as huggingface would typically produce a `training_args.bin` file. 

Any pointers?

`textattack attack --recipe deepwordbug  --num-examples 10 --model "checkpoint-500"`

**Comment by heytitle** [comment]
My interpretation from your question is that you're trying to use your own model. In this case, you probably have to the other options, e.g. `--model-from-file` or `--model-from-hugging-face`. 

This might be relevant: https://github.com/QData/TextAttack/blob/e83f4a0091fb1582893041148128cef482f970c3/textattack/commands/attack/attack_args_helpers.py#L41

**Comment by swayson** [comment]
Thanks @heytitle yep you are right. Turned out I had to use the `--model-from-file` argument.
