### ISSUE TITLE
model-from-file bug when absolute windows path provided.

### ISSUE THREAD

**Issue by swayson** [QData/TextAttack#225]
If an absolute windows path (e.g. C:\test.py) is passed to `--model-from-file` the following exception is raised:
```
# attack_args_helpers.py
        if ":" in args.model_from_file:
            model_file, model_name, tokenizer_name = args.model_from_file.split(":")

>>> ValueError: not enough values to unpack (expected 3, got 2)
```

Not sure what the reasoning of the check on `:` is but perhaps rather use `pathlib.Path` to check if valid path instead?

**Comment by jxmorris12** [comment]
Hey @swayson --

this is a total oversight on our part. We set up the command-line syntax to allow multiple parameters for a single arg -- in this case, `my_file.py:my_model:my_tokenizer` should indicate to load `my_model` and `my_tokenizer` from `my_file.py`.

We hadn't realized that this doesn't work on Windows, but we will fix it. I think we can replace `:` with `|`, does that sound right to you?

As a temporary fix, you can make that replacement yourself (`":"` with `"|"`) and hopefully that'll avoid the path errors on windows.
