### ISSUE TITLE
Not able to load my own model

### ISSUE THREAD

**Issue by ashwani-bhat** [QData/TextAttack#235]
I want to attack my own trained model. As such I used `textattack attack --model-from-file my_model.py --recipe bert-attack --num-examples 10`.  I am getting NameError: name 'load_model' is not defined. Kindly help.

**Comment by jxmorris12** [comment]
(solved on Slack)

the fix:
1. replace `load_model()` (sample function from documentation) with user's custom model-processing code, resulting in the following `my_model.py`:

```
import transformers
import textattack
from textattack.shared import utils
model_path = "./model_save/"
tokenizer = textattack.models.tokenizers.AutoTokenizer(model_path)
model = transformers.AutoModelForSequenceClassification.from_pretrained(model_path)
model = textattack.models.wrappers.HuggingFaceModelWrapper(model, tokenizer)
dataset = textattack.datasets.HuggingFaceNlpDataset(
  "imdb", shuffle = False
)
```

2. add `--dataset-from-file` command to let textattack know that you're loading a dataset from a file. final command:

```
textattack attack --model-from-file my_model.py --recipe bert-attack --num-examples 2
```
