### ISSUE TITLE
Mitigations for the attacks

### ISSUE THREAD

**Issue by kumarvrsec** [QData/TextAttack#237]
Are there any mitigations available for NLP models to defend against these attacks or make the model robust.I am thinking Adversarial training can be one.

**Comment by jxmorris12** [comment]
Hi @kumarvrsec – right now we support adversarial training via concatenating and replacing the dataset with perturbed examples. This is via `textattack train` with the `--attack` argument. We're planning on adding more defense techniques in the next few months.

**Comment by dsvrsec** [comment]
Hi,Are there any defense(mitigations) techniques that are added to textattack or available in the literature

**Comment by jxmorris12** [comment]
Hi @dsvrsec -- we enable adversarial training via `textattack train --attack`.
