### ISSUE TITLE
Sklearn model wrapper not working 

### ISSUE THREAD

**Issue by tsinggggg** [QData/TextAttack#241]
Hi,

I tried to follow the notebook in the official doc for attacking a logistic regression and got the error below. In the code below, it's assuming self.model is callable. 

~/anaconda3/lib/python3.7/site-packages/textattack/goal_functions/goal_function.py in _call_model_uncached(self, attacked_text_list)
    147         inputs = [at.tokenizer_input for at in attacked_text_list]
    148 
--> 149         outputs = self.model(inputs)
    150 
    151         assert len(inputs) == len(

TypeError: 'LogisticRegression' object is not callable

**Comment by jxmorris12** [comment]
Hey, did you fix it? @tsinggggg
