### ISSUE TITLE
GoalFunctionResult and AttackResult should have __str__

### ISSUE THREAD

**Issue by jxmorris12** [QData/TextAttack#242]
Both the `GoalFunctionResult` and `AttackResult` abstract classes should provide a meaningful `__str__` method so that they can be printed in a readable way.

**Comment by srujanjoshi** [comment]
I would like to submit a PR that fixes this.  What would be good information to print out about the GoalFunctionResult and AttackResult classes?

**Comment by VijayKalmath** [comment]
@jxmorris12  , 

The class AttackResult already has a __str__ function . 

https://github.com/QData/TextAttack/blob/d13575cedde5c4ba6c253f24c0a3ff0335ccd24e/textattack/attack_results/attack_result.py#L72

I have added a __repr__ function for GoalFunctionResult in #676 .
