### ISSUE TITLE
'Run in Colab' buttons not rendered on readthedocs

### ISSUE THREAD

**Issue by jxmorris12** [QData/TextAttack#244]
For some reason, the .ipynb HTML is formatted differently when displayed on Github/jupyter/jupyternb and readthedocs. The bit of HTML in each notebook that's intended to show buttons (like 'Run in Colab') doesn't render properly. We probably just need to fix the indentation, or maybe some setting in nbsphinx.

<hr>

**Screenshot of how it looks on github (good):**
<img width="827" alt="Screen Shot 2020-08-12 at 5 09 51 PM" src="https://user-images.githubusercontent.com/13238952/90068628-f6c19480-dcbe-11ea-9c6a-e947d1416144.png">

<hr>

**Screenshot of how it looks on readthedocs (bad):**
<img width="741" alt="Screen Shot 2020-08-12 at 5 09 55 PM" src="https://user-images.githubusercontent.com/13238952/90068631-f88b5800-dcbe-11ea-8d15-a6c77a73af17.png">

**Comment by MoosaSaadat** [comment]
I would like to provide a PR for this issue.

**Comment by bterrific2008** [comment]
[According to this issue](https://github.com/spatialaudio/nbsphinx/issues/468), HTML-style hyperlinks are not currently supported by `nbsphinx`. The content of the HTML-style hyperlink is generated as plain text, which accounts for why the buttons appear differently on readthedocs.

An solution could be replacing the buttons with Markdown image links. I was able to replace the "Run in Google Colab" button with a badge:

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb)

```[![Open In `Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb)```

I couldn't find an existing "View GitHub Source" badge online, but it shouldn't be difficult to make one with [shields.io](https://shields.io/).

One issue with this solution is that the image links are center aligned and not left aligned in the notebook. There should be a workaround using CSS, but I haven't been able to get it to work locally.

***

**Screenshot of how it looks on jupyter notebook:**

![image](https://user-images.githubusercontent.com/9489176/90326242-cdad3800-df3a-11ea-95ed-2c080c41d608.png)

**Screenshot of how it looks from the browser:**

![image](https://user-images.githubusercontent.com/9489176/90326351-3b0d9880-df3c-11ea-8041-a2135ab39444.png)

**Comment by jxmorris12** [comment]
Wow, thanks for figuring this out @bterrific2008 -- that sounds like a perfect solution. Do you mind submitting a pull request to fix the buttons?

**Comment by bterrific2008** [comment]
Will do!
