### ISSUE TITLE
Passing indices=[] to Attack.attack_dataset attacks the full dataset

### ISSUE THREAD

**Issue by jxmorris12** [QData/TextAttack#247]
Say `attack` is an instance of the `Attack` class. Calling `attack.attack_dataset(dataset, indices=[1, 3, 5, 7])` will run attacks on indices 1, 3, 5, and 7 of the dataset. 

It is common to omit the `indices` arugment: simply calling `attack.attack_dataset(dataset)` will run an attack on every sample in the dataset. Consequently, `attack.attack_dataset(dataset, indices=None)` will also run the attack on each sample in the dataset. 

However, now `attack.attack_dataset(dataset, indices=[])` attacks each sample in the dataset, too, since in Python, `[]` and `None` both evaluate to `False`. This is bad. If a user passes in `indices=[]`, we don't want to run an attack on every sample– we just want to return an empty list, and potentially print a warning message.

**Comment by jinyongyoo** [comment]
Fix by @MintForever
