### ISSUE TITLE
add BERT-based augmenter

### ISSUE THREAD

**Issue by jxmorris12** [QData/TextAttack#260]
We should allow data augmentation using masked-token prediction models through `WordSwapMaskedLM`. This would leverage the power of transformers like BERT to generate augmented inputs.

**Comment by qiyanjun** [comment]
@jinyongyoo @Hanyu-Liu-123 isn't this already part of the augmented?

**Comment by Hanyu-Liu-123** [comment]
@qiyanjun  I think we have the `EmbeddingAugmenter` that uses `transformation.WordSwapEmbedding`, but not an augmenter that uses `WordSwapMaskedLM`. CLARE actually have 3 transformations (including `WordSwapMaskedLM`) that uses masked-token prediction models. I'm thinking once we integrate CLARE maybe we can create a augmentation recipe that includes those mask-token transformations?

**Comment by Hanyu-Liu-123** [comment]
The masked-token augmentation has been merged into the master branch as the `CLAREAugmenter`!
