### ISSUE TITLE
Questions about new potential features

### ISSUE THREAD

**Issue by tsinggggg** [QData/TextAttack#264]
Hi, Thanks for the great work. It'd be great to have two new features for the package but I am not sure if it's in the roadmap.

The transformations and constraints based on word embeddings are using paragramcf embedding by default and it seems it's the only option, i wonder if it's possible for user to bring their own embedding?(maybe i can directly change the attributes related to embeddings but i guess this is probably not the expected way of using it)

Also for classification tasks, is it possible for user to define the cut-off probability for deciding labels, more generally the function f(softmax probs) --> labels?(currently it's taking whichever class has the highest prob).Let's say in a binary classification problem, i have a sample with true label 1 and predicted probability of 0.85, normally it's considered as correctly classified and will be skipped during the attack, but if i would like a 0.9 threshold then it's mislabelled.

Thank you!

**Comment by jxmorris12** [comment]
@tsinggggg thanks for the feedback. We can certainly add these things. Just wanted to clarify the first: are you suggesting to provide a word embedding file via the command line? Or just programmatically?

**Comment by tsinggggg** [comment]
> @tsinggggg thanks for the feedback. We can certainly add these things. Just wanted to clarify the first: are you suggesting to provide a word embedding file via the command line? Or just programmatically?

oh sorry for not being clear. I meant programmatically

**Comment by jxmorris12** [comment]
@tsinggggg for the second suggestion, can't you initialize an `UntargetedClassification` goal function with `target_max_score=0.9`? Let me know if I missed something there. (I'm looking at [untargeted_classification.py](https://github.com/QData/TextAttack/blob/master/textattack/goal_functions/classification/untargeted_classification.py))

**Comment by jxmorris12** [comment]
@tsinggggg I added the custom word embedding option in PR #274. Let me know if the goal function `target_max_score` isn't what you wanted – you can just reopen the issue if need be – and we'll work to fix that!

**Comment by FinTexIFB** [comment]
Hi. 

I would like to use textAttack for text augmentation. I plan to use the "EmbeddingAugmenter" on German text, which is why I need a German word embedding instead of "paragramcf".  I am not sure how to imple,ent this given your toolbox. How can I make use of your adjusted version of "word_embedding.py"?

Thank you very much for your help!

**Comment by jxmorris12** [comment]
Hi @FinTexIFB -- you should make a subclass of `WordSwap` that returns synonyms from the German word embedding dictionary for each word of input. 

You can implement the class however you want as long as you subclass WordSwap and implement `_get_replacement_words(self, word)` which should return the German embedding neighbors to `word` within your desired threshold. 

As you mentioned, [`word_embedding.py`](https://github.com/QData/TextAttack/blob/master/textattack/transformations/word_swap_embedding.py) provides a good template for doing so.
