### ISSUE TITLE
[Question] Can we use custom example to get textattack result 

### ISSUE THREAD

**Issue by panwarnaveen9** [QData/TextAttack#271]
Standard command like below will take the 10 sample from dataset it trained on and shows the result 

`textattack attack --model bert-base-uncased-sst2 --recipe bert-attack --num-examples 10`

How can I use same model and same recipe to attack sentence provided me ? not the from dataset. 

Example -
For sentence : `I really like the today's weather.` how can I get the result of attack on this sentence ?

**Comment by jxmorris12** [comment]
Hi @panwarnaveen9 -- if you have a lot of examples, you can use the `--dataset-from-file` argument. If you have few enough examples to test them all by hand, I suggest running `textattack attack --model bert-base-uncased-sst2 --recipe bert-attack --num-examples 10 **--interactive**` to try things out in interactive mode!

**Comment by panwarnaveen9** [comment]
@jxmorris12 Thanks.. 
This is awesome 👍 💯
