### ISSUE TITLE
Can this run on Win10?

### ISSUE THREAD

**Issue by KamiKazeFei** [QData/TextAttack#275]
When i try to install textattack in anaconda, pop this message
and i use pip list didn't see textattack in list,so can this package run on Win10 OS?
------------------------------------------------------------------------------------------

  Complete output (30 lines):
  running bdist_wheel
  running build
  running build_deps
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\User\AppData\Local\Temp\pip-install-pywzjr4w\torch\setup.py", line 225, in <module>
      setup(name="torch", version="0.1.2.post2",
    File "C:\Users\User\anaconda3\envs\text\lib\site-packages\setuptools\__init__.py", line 163, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\User\anaconda3\envs\text\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Users\User\anaconda3\envs\text\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Users\User\anaconda3\envs\text\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\User\anaconda3\envs\text\lib\site-packages\wheel\bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "C:\Users\User\anaconda3\envs\text\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\User\anaconda3\envs\text\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\User\anaconda3\envs\text\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Users\User\anaconda3\envs\text\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Users\User\anaconda3\envs\text\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\User\AppData\Local\Temp\pip-install-pywzjr4w\torch\setup.py", line 51, in run
      from tools.nnwrap import generate_wrappers as generate_nn_wrappers
  ModuleNotFoundError: No module named 'tools.nnwrap'
  ----------------------------------------
  ERROR: Failed building wheel for torch
  Running setup.py clean for torch
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\User\anaconda3\envs\text\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-pywzjr4w\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-pywzjr4w\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\User\AppData\Local\Temp\pip-install-pywzjr4w\torch
  Complete output (2 lines):
  running clean
  error: [Errno 2] No such file or directory: '.gitignore'
  ----------------------------------------
  ERROR: Failed cleaning build dir for torch
  Building wheel for lru-dict (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\User\anaconda3\envs\text\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-pywzjr4w\\lru-dict\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-pywzjr4w\\lru-dict\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\User\AppData\Local\Temp\pip-wheel-8gynp_k3'
       cwd: C:\Users\User\AppData\Local\Temp\pip-install-pywzjr4w\lru-dict\
  Complete output (17 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'lru' extension
  creating build
  creating build\temp.win-amd64-3.8
  creating build\temp.win-amd64-3.8\Release
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\User\anaconda3\envs\text\include -IC:\Users\User\anaconda3\envs\text\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" /Tclru.c /Fobuild\temp.win-amd64-3.8\Release\lru.obj
  lru.c
  creating C:\Users\User\AppData\Local\Temp\pip-install-pywzjr4w\lru-dict\build\lib.win-amd64-3.8
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\User\anaconda3\envs\text\libs /LIBPATH:C:\Users\User\anaconda3\envs\text\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.18362.0\um\x64" /EXPORT:PyInit_lru build\temp.win-amd64-3.8\Release\lru.obj /OUT:build\lib.win-amd64-3.8\lru.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.8\Release\lru.cp38-win_amd64.lib
  lru.obj : warning LNK4197: 指定了多次匯出 'PyInit_lru'，使用第一次的規格
     正在建立程式庫 build\temp.win-amd64-3.8\Release\lru.cp38-win_amd64.lib 和物件 build\temp.win-amd64-3.8\Release\lru.cp38-win_amd64.exp
  正在產生程式碼
  已完成程式碼產生
  LINK : fatal error LNK1158: 無法執行 'rc.exe'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1158
  ----------------------------------------
  ERROR: Failed building wheel for lru-dict
  Running setup.py clean for lru-dict
  Building wheel for editdistance (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\User\anaconda3\envs\text\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-pywzjr4w\\editdistance\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-pywzjr4w\\editdistance\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\User\AppData\Local\Temp\pip-wheel-e3cfsrll'
       cwd: C:\Users\User\AppData\Local\Temp\pip-install-pywzjr4w\editdistance\
  Complete output (31 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\editdistance
  copying editdistance\__init__.py -> build\lib.win-amd64-3.8\editdistance
  copying editdistance\_editdistance.h -> build\lib.win-amd64-3.8\editdistance
  copying editdistance\def.h -> build\lib.win-amd64-3.8\editdistance
  running build_ext
  building 'editdistance.bycython' extension
  creating build\temp.win-amd64-3.8
  creating build\temp.win-amd64-3.8\Release
  creating build\temp.win-amd64-3.8\Release\editdistance
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I./editdistance -IC:\Users\User\anaconda3\envs\text\include -IC:\Users\User\anaconda3\envs\text\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" /EHsc /Tpeditdistance/_editdistance.cpp /Fobuild\temp.win-amd64-3.8\Release\editdistance/_editdistance.obj
  _editdistance.cpp
  editdistance/_editdistance.cpp: warning C4819: 檔案含有無法在目前字碼頁 (950) 中表示的字元。請以 Unicode 格式儲存檔案 以防止資料遺失
  editdistance/_editdistance.cpp(117): error C2059: 語法錯誤: 'if'
  editdistance/_editdistance.cpp(118): error C2059: 語法錯誤: 'else'
  editdistance/_editdistance.cpp(119): error C2059: 語法錯誤: 'else'
  editdistance/_editdistance.cpp(120): error C2059: 語法錯誤: 'else'
  editdistance/_editdistance.cpp(121): error C2059: 語法錯誤: 'else'
  editdistance/_editdistance.cpp(122): error C2059: 語法錯誤: 'else'
  editdistance/_editdistance.cpp(123): error C2059: 語法錯誤: 'else'
  editdistance/_editdistance.cpp(124): error C2059: 語法錯誤: 'else'
  editdistance/_editdistance.cpp(125): error C2059: 語法錯誤: 'else'
  editdistance/_editdistance.cpp(126): error C2059: 語法錯誤: 'else'
  editdistance/_editdistance.cpp(127): error C2059: 語法錯誤: 'return'
  editdistance/_editdistance.cpp(128): error C2059: 語法錯誤: '}'
  editdistance/_editdistance.cpp(128): error C2143: 語法錯誤: 遺漏 ';' (在 '}' 之前)
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
  ----------------------------------------
  ERROR: Failed building wheel for editdistance
  Running setup.py clean for editdistance
Failed to build torch lru-dict editdistance
DEPRECATION: Could not build wheels for torch, lru-dict, editdistance which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: torchfile, websocket-client, pillow, tornado, jsonpointer, jsonpatch, pyzmq, visdom, shortuuid, python-dateutil, smmap, gitdb, GitPython, subprocess32, psutil, sentry-sdk, docker-pycreds, configparser, protobuf, promise, pathtools, watchdog, wandb, terminaltables, torch, lru-dict, language-tool-python, opt-einsum, wrapt, astunparse, google-pasta, pyasn1, pyasn1-modules, cachetools, rsa, google-auth, grpcio, werkzeug, absl-py, markdown, tensorboard-plugin-wit, oauthlib, requests-oauthlib, google-auth-oauthlib, tensorboard, tensorflow-estimator, termcolor, keras-preprocessing, gast, tensorflow, lemminflect, editdistance, pytz, pandas, tensorflow-hub, filelock, sacremoses, pyparsing, packaging, sentencepiece, tokenizers, transformers, sentence-transformers, kiwisolver, cycler, matplotlib, bert-score, tensorboardX, tabulate, lxml, boto, docutils, jmespath, botocore, s3transfer, boto3, smart-open, Cython, gensim, janome, py, colorama, more-itertools, pluggy, attrs, toml, atomicwrites, iniconfig, pytest, sqlitedict, bpemb, overrides, konoha, langdetect, decorator, networkx, cloudpickle, future, hyperopt, wcwidth, ftfy, mpld3, deprecated, segtok, flair, dill, pyarrow, xxhash, nlp, textattack
    Running setup.py install for torch ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\User\anaconda3\envs\text\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-pywzjr4w\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-pywzjr4w\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-8c2v9eg8\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\User\anaconda3\envs\text\Include\torch'
         cwd: C:\Users\User\AppData\Local\Temp\pip-install-pywzjr4w\torch\
    Complete output (23 lines):
    running install
    running build_deps
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\AppData\Local\Temp\pip-install-pywzjr4w\torch\setup.py", line 225, in <module>
        setup(name="torch", version="0.1.2.post2",
      File "C:\Users\User\anaconda3\envs\text\lib\site-packages\setuptools\__init__.py", line 163, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\User\anaconda3\envs\text\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\User\anaconda3\envs\text\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Users\User\anaconda3\envs\text\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\User\AppData\Local\Temp\pip-install-pywzjr4w\torch\setup.py", line 99, in run
        self.run_command('build_deps')
      File "C:\Users\User\anaconda3\envs\text\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\User\anaconda3\envs\text\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\User\AppData\Local\Temp\pip-install-pywzjr4w\torch\setup.py", line 51, in run
        from tools.nnwrap import generate_wrappers as generate_nn_wrappers
    ModuleNotFoundError: No module named 'tools.nnwrap'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\User\anaconda3\envs\text\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-pywzjr4w\\torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\User\\AppData\\Local\\Temp\\pip-install-pywzjr4w\\torch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\User\AppData\Local\Temp\pip-record-8c2v9eg8\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\User\anaconda3\envs\text\Include\torch' Check the logs for full command output.

**Comment by jxmorris12** [comment]
Hi @KamiKazeFei -- looks like you have torch 0.1.2 installed. You're going to need torch >= 1.0 to run TextAttack. Can you try upgrading torch and reinstalling? This should be able to run on Windows 10!

**Comment by jinyongyoo** [comment]
Closed because of no follow-up.
