### ISSUE TITLE
Conflicting versions(sentence-transformers, transformers) lead to failing tests

### ISSUE THREAD

**Issue by FlorianO** [QData/TextAttack#288]
Hi,
while following the Contribution Guideline i got the following problem:
`ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
sentence-transformers 0.3.7 requires transformers<3.4.0,>=3.1.0, but you'll have transformers 3.0.2 which is incompatible.
tensorflow 2.3.1 requires numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.2 which is incompatible.`

Due to this error 'make test' will have a lot of failing tests.
If i remove the version numbers for both libraries the tests will work (2 failing for other reasons)

**Comment by jinyongyoo** [comment]
Hi @FlorianO, we recently updated our `transformers` version to work with `sentence-transformers`.

**Comment by FlorianO** [comment]
I'll update and try again. :)
