### ISSUE TITLE
InputColumnModification and GreedyWordSwapWIR

### ISSUE THREAD

**Issue by tsinggggg** [QData/TextAttack#294]
This is probably very minor.. When the GreedyWordSwapWIR calculates the word importance, it calculates the leave one texts for all the words in the input, but if an input column modification constraint is specified, there's no need to calculate the word importance for the words in the column to ignore,

**Comment by jxmorris12** [comment]
Good point @tsinggggg! I believe GreedyWordSwapWIR could be faster by not ranking any words disallowed by pre-transformation constraints.

**Comment by VijayKalmath** [comment]
Thank you @tsinggggg  for opening this Issue. 

I looked at the other search methods aside from GreedyWordSwapWIR to check if the pre-transformation constraints can be used to optimize the number of queries. 

```
egrep “get_goal_results” *.py | egrep -o “*.+\.py” | uniq
beam_search.py
genetic_algorithm.py
greedy_word_swap_wir.py
particle_swarm_optimization.py
search_method.py
```
Amongst the four algorithms which call get_goal_results,
1) Optimized greedy_word_swap_wir.py 
2) Beam search calls get_transformations before get_goal_results so no optimization is possible.
3) Particle_swarm_optimization.py has  _get_best_neighbors uses get_transformations to get the initial population, so again no optimization is possible.
4) Similarly with genetic_algorithm.py, there are no get_goal_results calls before get_transformations 

Optimization of greedy_word_swap_wir.py is part of the PR opened - #665
