### ISSUE TITLE
Default for '--log-to-txt' (and -csv) tries to write to install tree

### ISSUE THREAD

**Issue by michaelkarlcoleman** [QData/TextAttack#308]
The default values for `--log-to-txt` and `--log-to-csv` tries to write into the install tree (e.g., where the .py files are).  This is bad in general and also specifically fails in a multi-user environment.

Instead, the default should be the current working directory, or perhaps somewhere under the home directory (though that would be confusing and less useful). 

As a workaround for other readers, specifying something like `--log-to-txt ./mylog.txt --log-to-csv ./mylog.csv` will get around this.

https://github.com/QData/TextAttack/blob/ecc010de65a90a49b62e7085d51681af31bea381/textattack/commands/attack/attack_args_helpers.py#L429-L474

**Comment by michaelkarlcoleman** [comment]
@github-actions LOL

Wish I could solve all of my problems so easily.

**Comment by jxmorris12** [comment]
This is already supported by TextAttack– as of a little while ago, the logger writes to the current directory (*not* the install tree, which I agree was quite bad!).
