### ISSUE TITLE
Missing citation in WordSwapMaskedLM

### ISSUE THREAD

**Issue by shizhouxing** [QData/TextAttack#313]
Hi, I find your [WordSwapMaskedLM](https://github.com/QData/TextAttack/blob/master/textattack/transformations/word_swap_masked_lm.py) transformation missed our paper https://arxiv.org/abs/1909.02560 where the technique of using BERT masked language model for generating substitution words in adversarial examples initially appeared, half a year earlier than the other two (BERT-attack and BAE) cited in your code (1909 v.s. 2004). 

We focused on paraphrase identification and did not claim using MaskedLM as a major contribution previously, but it was later claimed as the major contribution in BERT-attack and BAE. Would you mind checking it and adding a reference to our paper if you agree? Thanks!

**Comment by qiyanjun** [comment]
@shizhouxing I have added your paper link? https://github.com/QData/TextAttack/blob/master/textattack/transformations/word_swap_masked_lm.py

**Comment by shizhouxing** [comment]
@qiyanjun Thanks!
