### ISSUE TITLE
Unexpected behaviour when using customized word embedding

### ISSUE THREAD

**Issue by tsinggggg** [QData/TextAttack#325]
I was using `TextFoolerJin2019` to attack the distillbert sentiment analysis model from huggingface transformer `    from transformers import pipeline
    p = pipeline("sentiment-analysis")`, but i downloaded `https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz ` and replaced the original default paragram cf embedding in the recipe(one word embedding distance constrait and one word swap embedding transformation). I was using ['this is a bad movie', 0] as the input data.

The thing is in this vocab there are words like this: 'coulda_shoulda_woulda' and 'slovakia_slota_commented'. And among the attackedtexts, in some of them 'bad'  is replaced with complex words like these two. When this happens, these long words got tokenized and got broken into multiple words. One consequence is the 'newly_modified_indices' don't correspond correctly to the original sentence anymore. Therefore, list index of bound error occurs when checking the contraint.

To be specific, in this case where reference text is 'this is a bad movie' and attackedtext is 'this is a slovakia_slota_commented movie', in the code https://github.com/QData/TextAttack/blob/master/textattack/constraints/semantics/word_embedding_distance.py#L134, newly_modified_indices are 3,4,5 (representing slovakia, slota, commented after tokenization) and the reference_text has only length 5, therefore 5 will be out of bound.

I understand this maybe an unexpected way to use textattack, but i think it goes back to my previous wish list that textattack comes with its own ExceptionResult for any unexpected exceptions.

Also i think it's better to use defaultdict(dict) as the default for cos_sim_mat and mse_sim_mat, otherwise the statement in except block can fail:https://github.com/QData/TextAttack/blob/master/textattack/constraints/semantics/word_embedding_distance.py#L106
this test case fails
```
c = WordEmbeddingDistance(min_cos_sim=0.5)
c.cos_sim_mat = dict()
c.get_cos_sim(1, 10)
print(c.cos_sim_mat)
```
but this one passes
```
c = WordEmbeddingDistance(min_cos_sim=0.5)
c.cos_sim_mat = defaultdict(dict)
c.get_cos_sim(1, 10)
print(c.cos_sim_mat)
```

Thanks,

**Comment by tsinggggg** [comment]
One potential solution for this particular issue may be simply returning false when there are more than 1 newly_modified_indice

shttps://github.com/QData/TextAttack/blob/master/textattack/constraints/semantics/word_embedding_distance.py#L127

**Comment by tsinggggg** [comment]
![image](https://user-images.githubusercontent.com/20978879/98309559-c4ab9000-1f98-11eb-8c96-6b0003d7293d.png)

some of candidates shown here.. most of them make sense..

**Comment by tsinggggg** [comment]
https://github.com/QData/TextAttack/blob/07abaf5b1bc47beba534077c4086d7259e8d8e2b/textattack/shared/utils/strings.py#L26

I think the cause is here. Basically i think this is a tokenizing function but it only allows ' and - in words but not other special characters like * _ @.

If the corpus come from internet there's a high chance that words contain these ones, for example in the embedding trained on google news: https://s3.amazonaws.com/dl4j-distribution/GoogleNews-vectors-negative300.bin.gz there are words like coulda_shoulda_woulda and even sh_*_tty

**Comment by jinyongyoo** [comment]
I believe this out of bounds error occurs because how `AttackedText` tokenizes a text into words. Currently, it would split `slovakia_slota_commented` into `["slovakia", "slota", "commented"]`. We did not anticipate this use case, but I think we can also support words connected by `_` (currently we treat words connected by hypens as a single word). Also, I'm assuming that you want `slovakia_slota_commented` to be treated as a single "word", correct? 

I think an easy fix you can try on your end is to change line 35 [here](https://github.com/QData/TextAttack/blob/07abaf5b1bc47beba534077c4086d7259e8d8e2b/textattack/shared/utils/strings.py#L35) to `elif c in "'-_" and len(word) > 0:`. 

Could you maybe try this and see if it still raises out-of-bounds error?

**Comment by tsinggggg** [comment]
> I believe this out of bounds error occurs because how `AttackedText` tokenizes a text into words. Currently, it would split `slovakia_slota_commented` into `["slovakia", "slota", "commented"]`. We did not anticipate this use case, but I think we can also support words connected by `_` (currently we treat words connected by hypens as a single word). Also, I'm assuming that you want `slovakia_slota_commented` to be treated as a single "word", correct?
> 
> I think an easy fix you can try on your end is to change line 35 [here](https://github.com/QData/TextAttack/blob/07abaf5b1bc47beba534077c4086d7259e8d8e2b/textattack/shared/utils/strings.py#L35) to `elif c in "'-_" and len(word) > 0:`.
> 
> Could you maybe try this and see if it still raises out-of-bounds error?

Hey thanks for the response, this is exactly what i did and then i came into this word: sh_*_tty. lol.

**Comment by jinyongyoo** [comment]
Hmm I see. We did not consider those cases either. I think It's fine for us to allow words connected by `@` (emails) and `*`. Could you maybe make a PR about this? 

Also, I'll take a look into your suggestion about using defaultdict. We're planning to rewrite parts of the word embedding constraint and transformation to allow easier use of custom embeddings.

**Comment by tsinggggg** [comment]
any chance a new result type ExceptionResult is added when there's unexpected exceptions like this?

Sure, I'd love to.

Also i have written something for using custom embeddings. Not sure what you think about it, but here it is if it interests you.
https://github.com/tsinggggg/nlp_test/blob/master/nlptest/nlptest/testsuite/ta/util.py

**Comment by jinyongyoo** [comment]
Sure I agree clearer exceptions are more helpful for debugging. For custom embeddings, we actually came up with a wrapper for embedding (https://github.com/QData/TextAttack/blob/master/textattack/shared/word_embedding.py), but never fully integrated it with `WordSwapEmbedding` and `WordEmbeddingDistance`. We're planning to integrate it asap.

**Comment by qiyanjun** [comment]
@tsinggggg Possible to help us integrate the (https://github.com/QData/TextAttack/blob/master/textattack/shared/word_embedding.py), with WordSwapEmbedding and WordEmbeddingDistance. Plus adding your util code..? 

You can submit a PR then.. Many thanks,

**Comment by tsinggggg** [comment]
> @tsinggggg Possible to help us integrate the (https://github.com/QData/TextAttack/blob/master/textattack/shared/word_embedding.py), with WordSwapEmbedding and WordEmbeddingDistance. Plus adding your util code..?
> 
> You can submit a PR then.. Many thanks,

@qiyanjun Loved to!

**Comment by qiyanjun** [comment]
@tsinggggg many thanks! Please check out this page for the process: https://textattack.readthedocs.io/en/latest/1start/support.html

**Comment by qiyanjun** [comment]
this moves to PR https://github.com/QData/TextAttack/pull/333
