### ISSUE TITLE
Question about Evaluation Results of Model Zoo

### ISSUE THREAD

**Issue by Opdoop** [QData/TextAttack#358]
In the [Evaluation Results of Available Models](https://textattack.readthedocs.io/en/latest/3recipes/models.html#evaluation-results-of-available-models) section, all models have reported two results: *Successes* and *Accuracy*.  These two metrics seems always to be the same. As in the first `lstm-ag-news, Successes: 914/1000, Accuracy: 91.4%`. 
According to the document, in my understanding, this result should be the accuracy on normal test/val data split of the available models. 
My question is what's the meaning of `Successes` in this section? Is it some attack success rate or just the same meaning of `Accuracy` ?

**Comment by qiyanjun** [comment]
@Opdoop yes. we should rename that as Accuracy. I Will update in the next merge.
