### ISSUE TITLE
Parallel flag seems to be broken

### ISSUE THREAD

**Issue by Cryptiex** [QData/TextAttack#359]
When I create adversial samples with

`textattack attack --recipe pwws --model lstm-imdb --num-examples 120000 --dataset-from-huggingface imd `

everything works perfectly.

If I use the `--parallel` options, though, it seems to break. It stays at 0% forever.

`textattack attack --recipe pwws --model lstm-imdb --num-examples 100 --dataset-from-huggingface imdb --parallel                                                                                                                                                   Reusing dataset imdb (/home/lukas.huber/.cache/huggingface/datasets/imdb/plain_text/1.0.0/90099cb476936b753383ba2ae6ab2eae419b2e87f71cd5189cb9c8e5814d12a3)  textattack: Loading datasets dataset imdb, split test.                                                                                                       textattack: Running on 8 GPUs                                                                                                                                  0%| `

**Comment by jinyongyoo** [comment]
Hi @Cryptiex, I ran`textattack attack --recipe pwws --model lstm-imdb --num-examples 100 --dataset-from-huggingface imdb --parallel` on our 8 gpu server and the `--parallel` option works fine. Could you maybe try other models (e.g. BERT) and provide us with more information?

**Comment by Cryptiex** [comment]
![textattack](https://user-images.githubusercontent.com/24294489/100723262-d890b900-33c1-11eb-8d1c-f3f18f32ae77.PNG)

When I execute the command the progress bar does not progress at all. It simply stays at 0%

**Comment by Cryptiex** [comment]
Any updates on this?

**Comment by jinyongyoo** [comment]
I sorry for the delay. I don't really have any good updates because I'm having a hard time recreating the error (`--parallel` seems to work on all of the machines I've tried so far). 

Can you copy the following code and run it as a script? It evaluates the accuracy of BERT IMDB model via the same multiprocessing method as TextAttack. Let me know if your machine still hangs with the script. Then, it might be a problem with your machine.

**Comment by qiyanjun** [comment]
@Cryptiex can you provide more details? on what OS? what version of Python? inside what environment?
