### ISSUE TITLE
Difference between Search method of "TextBugger recipe" and the paper

### ISSUE THREAD

**Issue by threemmm** [QData/TextAttack#363]
In _textbugger_li_2018.py_ search method is `GreedyWordSwapWIR()` , whose default arg is 'unk', but in the paper, they proposed a scoring function that removes a word to find the important word.
So I think `GreedyWordSwapWIR(wir_method="delete")`  should be defined in _textbugger_li_2018.py_ as the search method.

**Comment by qiyanjun** [comment]
@threemmm thanks. We will check

**Comment by jinyongyoo** [comment]
fixed by PR #373.
