### ISSUE TITLE
Parallel Attack RuntimeError: generator raised StopIteration

### ISSUE THREAD

**Issue by Opdoop** [QData/TextAttack#366]
Uss recipe `textbugger`attack `imdb^test` dataset, get `RuntimeError: generator raised StopIteration`
The trackback is below:
```
  File "/u01/jh/Github/TextAttack/textattack/commands/attack/attack_command.py", line 47, in run
    run_parallel(args)
  File "/u01/jh/Github/TextAttack/textattack/commands/attack/run_attack_parallel.py", line 151, in run
    raise result
RuntimeError: generator raised StopIteration
```
I tried in python 3.7 with torch 1.7 and torch 1.6. Also python 3.6 with torch 1.6. This RuntimeError keeps show up in all these environments, although in different iterations.

**Comment by jinyongyoo** [comment]
Could you tell us the full command you ran?

**Comment by Opdoop** [comment]
@jinyongyoo 
I run python script, below command could reproduce the bug
```
textattack attack --recipe textbugger --model lstm-imdb --num-examples 25000 --parallel --disable-stdout
```
 except the traceback didn't maintain `RuntimeError` just show `None` instead.

**Comment by Opdoop** [comment]
Around 8323/25000 examples will occur this error

**Comment by jinyongyoo** [comment]
@Opdoop This might be an issue related to issue #371.

**Comment by lethaiq** [comment]
@jinyongyoo @Opdoop this is indeed related to #371. It took me 2 hours to trace this back to the `words_from_text()`

**Comment by Opdoop** [comment]
@lethaiq Woo~ Looking forward to your PR~
p.s. Is there any chance that `words_from_text` also related to bug #362 ?

**Comment by jinyongyoo** [comment]
@Opdoop Can you try running the attack again to see if the latest patch fixed it?

**Comment by Opdoop** [comment]
@jinyongyoo  Yes, the hot-fix solved this bug. 🎉

**Comment by jinyongyoo** [comment]
Okay great! I'll close this and #362.

**Comment by ziqi-zhang** [comment]
@Opdoop @jinyongyoo Hi, I encountered a similar problem when using textbugger attack. Can you please tell me where and how should I change the code to hot-fix this bug? Thanks!

**Comment by lethaiq** [comment]
@ziqi-zhang just pull the latest version it should already has the patch for this
