### ISSUE TITLE
Function words_from_text() does not account possible Homoglyph characters

### ISSUE THREAD

**Issue by lethaiq** [QData/TextAttack#371]
Currently, the function `words_from_text()` from `string.py` will not correctly output if the perturbed word in a sentence is Homoglyph. For example: `words_from_text("×") will` return an empty list.

This can lead to unexpected behaviors when using `TextBugger` attack.

**Comment by jinyongyoo** [comment]
Thanks for raising this issue. We'll review it.

**Comment by lethaiq** [comment]
@jinyongyoo my temporary solution is just copying the `self.homos` dictionary from `WordSwapHomoglyphSwap` class to `words_from_text() `. We might want to make this dictionary global to remove duplication. Thanks for great repo.

**Comment by jinyongyoo** [comment]
Yes that's one way to fix the issue, though how `words_from_text` work might change in the near future. If you don't mind, could you still make a PR of your temporary solution as a hotfix? Thanks.

**Comment by Opdoop** [comment]
Hi @lethaiq, I may encounter the same bug. Hotfix would be very helpful~

**Comment by jinyongyoo** [comment]
Fixed by PR #376
