### ISSUE TITLE
Incongruent version for 0.2.14 when installing with pip 

### ISSUE THREAD

**Issue by Tambup** [QData/TextAttack#375]
Hi, we are working on with #370 and surprisingly we discovered that when installing with pip the library some file(s) doesn't correspond to the files on the release 0.2.14 in git.
More in detail, we want to use the WordEmbedding class and as suggested in #370 we use these parameters embedding_matrix, word2index, index2word and nn_matrix. Here the issue is that we get this error:

> NameError                                 Traceback (most recent call last)
> 
> <ipython-input-4-ec6458707cde> in <module>()
----> 1 wb = WordEmbedding(embedding_matrix=embedding_matrix,
      2                    word2index=word2index,
      3                    index2word=index2word)
> 
> NameError: name 'embedding_matrix' is not defined

We browsed into the passed release and discovered that the library installed with pip has the file textattack/shared/word_embedding.py equivalent to 0.2.12.
So we tryied to install manually from git:

> git clone https://github.com/QData/TextAttack
pip install -e ./TextAttack

and than:
`import TextAttack`

`WordEmbedding(embedding_matrix=embedding_matrix,
                                word2index=word2index,
                                index2word=index2word)`
This way the code with embedding_matrix, word2index, index2word and nn_matrix is running properly.
We guess that the code on the repository used by pip is not the same of github.com/QData/TextAttack/archive/0.2.14.tar.gz

By the way, congratulation for the great work (and the great doc that helped us finding the issue).

**Comment by jinyongyoo** [comment]
Yes that might be because the PR for the custom word embeddings was made after the 0.2.14 release. Seems like the PR was merged on 11/27 while 0.2.14 was released on 11/18. We'll make a new release soon to fix this. Thanks for pointing it out!

**Comment by Tambup** [comment]
The bug is solved with the new release 1adc909d748ecff2a74c7aceba58eff3744766b3.
