### ISSUE TITLE
Feature Request: specify which split when attack

### ISSUE THREAD

**Issue by lethaiq** [QData/TextAttack#377]
I think by default the CLI command `textattack attack` will use the train split of the dataset. We might want to specify which split of the dataset to use to attack. E.g., `textattack attack --model cnn-mr --split test`

**Comment by jxmorris12** [comment]
This is a good point! We should probably require the `--split` flag; if not, we should default to test, or dev.

**Comment by qiyanjun** [comment]
This is solved by PR https://github.com/QData/TextAttack/pull/400
