### ISSUE TITLE
The transferability and the types of attacks

### ISSUE THREAD

**Issue by ziqi-zhang** [QData/TextAttack#379]
Hi,
I see you implement plenty of attack recipes and most of them are greedy methods. I wonder among these attacks, is there anyone that uses the white-box information, such as the gradient of the model w.r.t. input? And which one has better transferability between different models?

Thanks,

**Comment by lethaiq** [comment]
@ziqi-zhang I can see that `Hotflip` is a white-box and needs access to the model's gradients. I am not sure about the transferability, and correct me if I am wrong but we do not have cross-model attack function yet in the package.

**Comment by ziqi-zhang** [comment]
Hi @lethaiq , thanks for your quick reply. I tried hotflip on BERT-base-uncased with glue dataset, but I got the error ValueError: Cannot perform GradientBasedWordSwap on model BertForSequenceClassification. Issue #256 mentioned this problem. It seems that the feature is not added yet. I was wondering is it possible to use another tokenizer in this case?

**Comment by jinyongyoo** [comment]
As Jack said in that issue, we don't allow BERT because it's a word-level tokenization. I think what you could do is for each word, find the best embedding/token via the gradient, then check if the token is actually a word or not (which could be tricky). You can refer to our WordSwapMaskedLM transformation for examples of how we do this, though it's not guaranteed that the token will actually be a standalone word.

**Comment by ziqi-zhang** [comment]
Hi @jinyongyoo , thanks for your suggestion! I think you mean the file TextAttack/textattack/transformations/word_swaps/word_swap_masked_lm.py .  I will refer to that.

**Comment by ziqi-zhang** [comment]
@jinyongyoo BTW, if I want to try hotflip attack, which model and dataset should I use? Sorry for such a simple question because I didn't find it on the document.

**Comment by lethaiq** [comment]
@ziqi-zhang you can try LSTM with any of the datasets:
`textattack attack cnn-mr --recipe hotflip`

From what I understand, only LSTM supports hotflip now.

**Comment by ziqi-zhang** [comment]
@lethaiq OK, thanks!!
