### ISSUE TITLE
Add new attack recipe

### ISSUE THREAD

**Issue by RishabhMaheshwary** [QData/TextAttack#385]
Request to add a new attack recipe:
 **Generating Natural Language Attacks in a Hard Label Black Box Setting**, accepted in AAAI 2021 main conference.
Paper: [Link to paper](https://www.researchgate.net/publication/347304785_Generating_Natural_Language_Attacks_in_a_Hard_Label_Black_Box_Setting).
Code: [Link to code](https://github.com/RishabhMaheshwary/hard-label-attack).

Brief Outline:
The paper proposes a novel decision based attack strategy that utilizes population-based optimization algorithm to generate adversarial examples by observing only the topmost predicted label.

**Comment by jinyongyoo** [comment]
Hi @RishabhMaheshwary, thank you sharing the paper. If you don't mind, could you make a PR for the new attack recipe? Please feel free to create any new components (e.g. search method, transformation, constraint) that is needed for your attack. 

While most of the recipes have been added by TextAttack developers, we also would like to have some community input and feedback. If you have any questions or issues please let me know! You can either create Github issues or directly ask questions in our [slack channel](https://join.slack.com/t/textattack/shared_invite/zt-huomtd9z-KqdHBPPu2rOP~Z8q3~urgg).

**Comment by RishabhMaheshwary** [comment]
Sure, first I will try to understand the implementation of existing attack recipes and then will open a PR for the new recipe.

**Comment by srujanjoshi** [comment]
Closed since a corresponding Pull Request has been created.
