### ISSUE TITLE
How to save the generated adversarial examples?

### ISSUE THREAD

**Issue by zedzx1uv** [QData/TextAttack#386]
Hi! I wang to compute the semantic similarity between the orig texts and the adv texts, but they are output on the screen.  How do I save them to a file?

**Comment by RishabhMaheshwary** [comment]
You can use the following:
```
--log-to-csv outputs/ --csv-style plain
```
It will save the results as a csv file in ```outputs``` folder.

**Comment by zedzx1uv** [comment]
thank you very much for your help！！
