### ISSUE TITLE
Problems with file redirection

### ISSUE THREAD

**Issue by nbrgr** [QData/TextAttack#388]
I'm running textattack on our compute cluster and the job scheduler redirects stdout to a file. Textattack's formatting should check if the output is a tty or not and disable color and formatting if the output doesn't support it.

Example output when file is redirected:
```
^MESC[34;1mtextattackESC[0m: Loading ESC[94mdatasetsESC[0m dataset ESC[94myelp_polarityESC[0m, split ESC[94mtestESC[0m. Downloading and preparing dataset yelp_polarity/plain_text (download: 158.67 MiB, generated: 421.28 MiB, post-processed: Unknown size, total: 579.95 MiB)
```

**Comment by jinyongyoo** [comment]
Good point. We'll add an option to disable color output
