### ISSUE TITLE
Infinite loop in augment function

### ISSUE THREAD

**Issue by duongkstn** [QData/TextAttack#389]
Hi,
In function `augment` of class `Augmenter`, you wrote: `while words_swapped < num_words_to_swap:` . But when `words_swapped` is always smaller than `num_words_to_swap` , **the while loop becomes infinite.**
**For example:**
Assume I have a sentence with 18 words and `pct_words_to_swap== 0.15`, then `num_words_to_swap == 2`. Otherwise, I have a `Transformation` function `f` which only replace one word of a sentence at a time (example: replace the first word) . So `words_swapped` always equals to 1 and the while loop will not stop.
Please help me to tackle this problem

**Comment by Hanyu-Liu-123** [comment]
Hi duongkstn, thank you for bringing up this issue! I'll think about what we could do to avoid this and get back to you

**Comment by qiyanjun** [comment]
@Hanyu-Liu-123 this is definitely an issue. It also relates to the non-caching in the Augmenter class...

**Comment by qiyanjun** [comment]
solved by https://github.com/QData/TextAttack/pull/368
