### ISSUE TITLE
Documentation on text attack for local models.

### ISSUE THREAD

**Issue by xinjiefan** [QData/TextAttack#395]
Thank you for providing such a good codebase! I am wondering could you please elaborate on using the code for locally trained models? I have used modified huggingface's code to train a local model. I am wondering what would an example to load the model, when the model is not standard huggingface code? (So different from https://github.com/QData/TextAttack/issues/235)

Many thanks to you!!

**Comment by jinyongyoo** [comment]
Hi @xinjiefan. Could you specify whether it's a `transformers` model or a typical PyTorch model. If it's something you can load via `from_pretrained`, you can still use the method from #235. If it's a PyTorch model, the method for loading the model will still be similar.  For example, if it's a PyTorch LSTM model, what you can do is 

```
import textattack
state_dict = # load saved state dict
model = ModelClass()
model.load_state_dict(state_dict)
tokenizer = # load saved tokenizer
model = textattack.models.wrappers.PyTorchModelWrapper(model, tokenizer)
```

Then, save the code as a python file, then pass the path of the file to `--model-from-file` argument.

**Comment by xinjiefan** [comment]
Thanks a lot for the explanation! It really helped! I will close the issue.

**Comment by zmf0507** [comment]
@jinyongyoo  can you tell how can I load pre-trained LSTM and Word-CNN models ?
I tried with model = LSTMForClassification(model_path="lstm-sst2") but it gives error that "Exception: Could not find lstm-sst2 on server."
Please let me know. thanks

**Comment by zmf0507** [comment]
@jinyongyoo  Also please tell whats the correct path to be passed for loading Word CNN models as well ?
