### ISSUE TITLE
Understanding labels of pretrained models

### ISSUE THREAD

**Issue by kanishkamisra** [QData/TextAttack#397]
Hi, thanks for this wonderful project! I was trying to use your pretrained models for an NLI evaluation task but I got a little confused on what labels do the ambiguously labelled "LABEL_0", "LABEL_1", and "LABEL_2" correspond to. Any pointers would be appreciated!

My preliminary guess is that LABEL_1 is "Entailment" but that's just by running some sanity checks such as using the same premise as the hypothesis, using an obvious pair of entailing instances, etc.

**Comment by veronica320** [comment]
Same issue here. A couple of sanity checks actually give inconsistent results, e.g. using [bert-base-uncased-snli](https://huggingface.co/textattack/bert-base-uncased-snli), "I love you. I love you" has LABEL_2 as the prediction, while "I like you. I like you" would have LABEL_1. 
Could it be clarified please? Thanks in advance!

**Comment by veronica320** [comment]
Hi there, is there any update on this? 
Thanks in advance!

**Comment by qiyanjun** [comment]
This certainly needs to be documented. It is more about datasets and how we use them. Please stay tuned.. trying to figure out with a student

**Comment by cogeid** [comment]
You can check the labels by clicking on the following link. Scroll all they way to the bottom and you will see a model chart. The fourth column of the chart shows output types.

https://textattack.readthedocs.io/en/latest/3recipes/models.html
