### ISSUE TITLE
textattack/xlnet-large-cased-QQP got only acc:63.18% f1:0

### ISSUE THREAD

**Issue by anaivebird** [QData/TextAttack#404]
**Describe the bug**
textattack/xlnet-large-cased-QQP got only acc:63.18% f1:0
Model is got from huggingface model hub

**To Reproduce**
model link here:https://huggingface.co/textattack/xlnet-large-cased-QQP
ways to evaluate it on QQP:
run https://colab.research.google.com/github/huggingface/notebooks/blob/master/examples/text_classification.ipynb
only need to change model_checkpoint to "textattack/xlnet-large-cased-QQP"

**Expected behavior**
get correct acc and F1

**Screenshots or Traceback**
{'textattack/xlnet-large-cased-QQPQQP': {'eval_loss': 0.6836028099060059, 'eval_accuracy': 0.6318327974276527, 'eval_f1': 0.0, 'eval_runtime': 183.5566, 'eval_samples_per_second': 220.259}}

**System Information (please complete the following information):**
 - run on colab above

**Comment by qiyanjun** [comment]
@tahmid-kazi can you check this model?

**Comment by srujanjoshi** [comment]
Will check this model.

**Comment by jxmorris12** [comment]
I think this is a tokenization issue. But the model is clearly broken as-is, so I'm going to remove it from the Hub while we investigate. Sorry for your trouble @[anaivebird](https://github.com/anaivebird)!
