### ISSUE TITLE
License of the pretrained models

### ISSUE THREAD

**Issue by ksmultiacc3** [QData/TextAttack#405]
could you please tell what is the license of the pretrained models available in : https://textattack.readthedocs.io/en/latest/3recipes/models.html  ?

**Comment by jinyongyoo** [comment]
TextAttack uses MIT license. But the most of the pretrained models are created and trained using the transformers library which uses Apache License 2.0. So I'm not sure if Apache License 2.0 also applies in this situation. I hope that answers your question.
