### ISSUE TITLE
Augmenting Chinese Text

### ISSUE THREAD

**Issue by suckseed5** [QData/TextAttack#411]
Hi, 
    I have some questions to ask you about text expansion  and hope you can answer the following for me.Thank you very much.
    Does textattack augment support Chinese? I tested the Chinese text here and found that augmentation has not changed.

textattack augment --csv examples.csv --input-column text --recipe embedding --pct-words-to-swap .1 --transformations-per-example 3 --exclude-original --overwrite

textattack: Preparing to overwrite augment.csv.
textattack: Read 180 rows from examples.csv. Found columns {'text', 'label'}.
Augmenting rows: 100%|█████████████████████████| 180/180 [00:00<00:00, 371.54it/s]
textattack: Wrote 180 augmentations to augment.csv in 0.4882683753967285s.

**Comment by jinyongyoo** [comment]
@suckseed5 We are working on adding support for other languages (e.g. chinese) right now! So seems like what you're attempting to do right now is replace Chinese with English transformation. That probably won't work right out of the box.

**Comment by suckseed5** [comment]
@jinyongyoo Thank you very much for your suggestion.I will try it.
