### ISSUE TITLE
Possible issue with implementation of CLARE

### ISSUE THREAD

**Issue by QuintinPope** [QData/TextAttack#412]
**Describe the bug**
I think textattack's CLARE implementation differs from the paper (though I may be wrong)

**To Reproduce**
CLARE invokes BeamSearch with a beam width of 1.

As I understand textattack's BeamSearch method, given an initial text, textattack uses CLARE to generate a set of perturbations, chooses the perturbation that most changes the classification, then generates a new set of perturbations **based on the newly perturbed text.**

The issue is that the CLARE algorithm (Algorithm 1 from: [here](https://arxiv.org/pdf/2009.07502.pdf)) completely separates generating perturbations and the greedy search. There's no mechanism for future perturbations to be conditioned on a past perturbation. 

Am I misunderstanding how textattack BeamSearch works, or is the textattack implementation of CLARE different from the paper?

Thanks for your help

**Expected behavior**
Invoking CLARE with textattack should match the algorithm proposed in the paper.

**Screenshots or Traceback**
If applicable, add screenshots to help explain your problem. Also, copy and paste tracebacks produced by the bug. 

**System Information (please complete the following information):**
 - OS: [e.g. MacOS, Linux, Windows]
 - Library versions (e.g. `torch==1.7.0, transformers==3.3.0`)
 - Textattack version

**Additional context**

**Comment by qiyanjun** [comment]
Great question. Our CLARE implementation has been agreed upon by the CLARE author.
