### ISSUE TITLE
Attack to custom NLI dataset 

### ISSUE THREAD

**Issue by Opdoop** [QData/TextAttack#414]
In https://github.com/QData/TextAttack#dataset-from-a-file, example formation is (input, output). As:
```
dataset = [('Today was....', 1), ('This movie is...', 0), ...]
```
But for NLI dataset, every input instance is 2 paired sentences. How to formate a custom NLI dataset (attack bert-based model)? Any hint would be helpful~

p.s. Command-line like `textattack attack --recipe textfooler --model bert-base-uncased-snli --num-examples 100` could attack NLI model and result prity well🎉

**Comment by Opdoop** [comment]
Solved. For NLI dataset, `dataset` is still a iterable of `(input, output)` pair. Below is an example:
```
# initial
dataset = []	

# label mapping, different from huggingface datasets mapping
label2id = {'entailment': 1,
            'neutral': 2,
            'contradiction': 0}

# an input instance
premise = 'Two boys inside a fence jump in the air while holding a basketball .'
hypothesis = 'Two boys sit down .'
label = 'contradiction'	

# formation
input = collections.OrderedDict(
            [('premise', premise),
             ('hypothesis', hypothesis)]
        )
output = label2id[label]

# build
dataset.append((input, output))
```

**Comment by penguinnnnn** [comment]
So the form of dataset should be:
```
[({'premise': xxx, 'hypothesis': xxx}, 1), ...]
```
Right?
