### ISSUE TITLE
Unsuccessful checks on minimize_bleu.py

### ISSUE THREAD

**Issue by farigys** [QData/TextAttack#416]
Hi,

Seems like minimize_bleau.py has failed some checks, and I could not see which checks it failed. Do these fails affect the code in any way?
https://github.com/QData/TextAttack/blob/b7b036aa362029b8876347af00fa7dcbac2967bc/textattack/goal_functions/text/minimize_bleu.py#L17

**Comment by jxmorris12** [comment]
@farigys - the tests all pass now, so I think we're ok! :)
