### ISSUE TITLE
The expected functionality of `DeletionAugmenter`

### ISSUE THREAD

**Issue by gpengzhi** [QData/TextAttack#426]
**Describe the bug**

Hi, I want to know the functionality of `DeletionAugmenter`. This augmenter returns only one word even though I set `pct_words_to_swap` to be 0.1.

**To Reproduce**
```python
from textattack.augmentation import DeletionAugmenter

augmenter = DeletionAugmenter(transformations_per_example=10, pct_words_to_swap=0.1)
s = "The United States and China may soon reach a trade agreement."
augmenter.augment(s)
```

```
['China.',
 'China.',
 'The.',
 'United.',
 'United.',
 'United.',
 'reach.',
 'reach.',
 'soon.',
 'trade.']
```

**Expected behavior**

**Screenshots or Traceback**
If applicable, add screenshots to help explain your problem. Also, copy and paste tracebacks produced by the bug. 

**System Information (please complete the following information):**
 - OS: MacOS
 - Library versions torch==1.6.0
 - Textattack version: 0.2.15

**Additional context**

**Comment by akkarimi** [comment]
I'm having the same problem. 
I'm trying to augment some data with EDA where DelectionAugmenter class is also used. 
Some of the augmented lines that are returned contain only one word while the original consists of more than 20 words.
