### ISSUE TITLE
pre-processing required for getting same results on your pre-trained lstm/cnn models

### ISSUE THREAD

**Issue by zmf0507** [QData/TextAttack#427]
Hello,
Can you tell me what exact text-cleaning and pre-processing steps are required on input text if I am evaluating them on text-attack pre-trained lstm and CNN models? 
As of now, I remove special characters, punctuations and numbers and pass it to tokenizer.encode().
Please let me know.

**Comment by srujanjoshi** [comment]
Hey there unless you weren't figure this out by now, the answer to that question is dependent on the specific pre-trained model you plan to use.  

The Model Zoo page in the documentation might be useful:
https://textattack.readthedocs.io/en/latest/3recipes/models.html#training-details-for-each-textattack-model

You can also check out TextAttack's model hub on HuggingFace:
https://huggingface.co/textattack?sort=alphabetical
