### ISSUE TITLE
Offset argument doesnot work with custom dataset

### ISSUE THREAD

**Issue by fyse-nassar** [QData/TextAttack#432]
**Describe the bug**

To do an attack on the custom dataset, the command as per the documentation is 

`textattack attack --recipe clare --model albert-base-v2-yelp --dataset-from-file my_dataset.py --num-examples 500 --num-examples-offset 0 --shuffle False --log-to-csv "./attack_output.csv" --csv-style plain
`

The above command iterates over the dataset from the first example. But if I want to skip the first 10 examples of my custom dataset I set the `--num-examples-offset 10`. But on doing this, the attack **still begins from the start of the dataset** and doesn't skip any examples.

**To Reproduce**
1. Use a custom dataset as mentioned in the documentation.
2.  Vary the `--num-examples-offset` value to see that the attack always begins from the start of the dataset.

**Expected behavior**
 `--num-examples-offset` should actually skip the examples

**System Information:**
 - OS: [Linux]
 - Library versions (mentioned below)
 
<details><summary>requirements.txt</summary>
<p>

```
absl-py==0.11.0
astunparse==1.6.3
beautifulsoup4==4.9.3
bert-score==0.3.7
bpemb==0.3.2
cachetools==4.2.1
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
cloudpickle==1.6.0
cycler==0.10.0
datasets==1.3.0
decorator==4.4.2
Deprecated==1.2.11
dill==0.3.3
docopt==0.6.2
editdistance==0.5.3
filelock==3.0.12
flair==0.6.1.post1
flatbuffers==1.12
fsspec==0.8.7
ftfy==5.9
future==0.18.2
gast==0.3.3
gdown==3.12.2
gensim==3.8.3
google==3.0.0
google-auth==1.27.0
google-auth-oauthlib==0.4.2
google-pasta==0.2.0
grpcio==1.32.0
h5py==2.10.0
huggingface-hub==0.0.2
hyperopt==0.2.5
idna==2.10
importlib-metadata==3.7.0
Janome==0.4.1
joblib==1.0.1
Keras-Preprocessing==1.1.2
kiwisolver==1.3.1
konoha==4.6.2
langdetect==1.0.8
language-tool-python==2.5.2
lemminflect==0.2.1
lru-dict==1.1.7
lxml==4.6.2
Markdown==3.3.4
matplotlib==3.3.4
more-itertools==8.7.0
mpld3==0.3
multiprocess==0.70.11.1
networkx==2.5
nltk==3.5
num2words==0.5.10
numpy==1.18.5
oauthlib==3.1.0
opt-einsum==3.3.0
overrides==3.0.0
packaging==20.9
pandas==1.2.3
Pillow==8.1.1
protobuf==3.15.3
pyarrow==3.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==2.4.7
PySocks==1.7.1
python-dateutil==2.8.1
pytz==2021.1
regex==2020.11.13
requests==2.25.1
requests-oauthlib==1.3.0
rsa==4.7.2
sacremoses==0.0.43
scikit-learn==0.24.1
scipy==1.4.1
segtok==1.5.10
sentencepiece==0.1.95
six==1.15.0
smart-open==4.2.0
soupsieve==2.2
sqlitedict==1.7.0
tabulate==0.8.9
tensorboard==2.4.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.4.1
tensorflow-estimator==2.4.0
tensorflow-gpu==2.4.1
tensorflow-hub==0.11.0
termcolor==1.1.0
terminaltables==3.1.0
textattack==0.2.15
threadpoolctl==2.1.0
tokenizers==0.10.1
torch==1.7.1
tqdm==4.49.0
transformers==4.3.3
typing-extensions==3.7.4.3
urllib3==1.26.3
wcwidth==0.2.5
Werkzeug==1.0.1
word2number==1.1
wrapt==1.12.1
xxhash==2.0.0
zipp==3.4.0
```
</p>
</details>

**Comment by donggrant** [comment]
I can't seem to reproduce this problem. I ran a short example with the custom dataset 
`dataset = [("I enjoyed the movie a lot!", 1), ("Absolutely horrible film.", 0), ("Our family had a fun time!", 1)]` 
and ran 
`textattack attack --recipe clare --model albert-base-v2-yelp --dataset-from-file my_dataset.py --num-examples 500 --num-examples-offset 2 --log-to-csv "./attack_output.csv"` 
and it successfully ran only the 3rd example. I realize this was an old issue, so this bug may have already been resolved.
