### ISSUE TITLE
WordSwapInflections can't be used.

### ISSUE THREAD

**Issue by 24kb-star** [QData/TextAttack#435]
**Describe the bug**
I used WordSwapInflections, but it can't generate new sentence. I debug the code and found the pos model's ouput isn't corresponding with self._enptb_to_universal in word_swap_inflections.py. When I modify the code, it works.

**To Reproduce**
First use TextAttack, the pos model was download itself.

**Expected behavior**

**Screenshots or Traceback**
If applicable, add screenshots to help explain your problem. Also, copy and paste tracebacks produced by the bug. 

**System Information (please complete the following information):**
 - OS: [e.g. MacOS, Linux, Windows]
 - Library versions (e.g. `torch==1.7.0, transformers==3.3.0`)
 - Textattack version

**Additional context**

**Comment by jxmorris12** [comment]
@24kb-star you mentioned that you made a modification to the code to get this type of word-swapping to work on your system. Can you explain further?
