### ISSUE TITLE
Compatible problem in Win10 & ssl certificate problem

### ISSUE THREAD

**Issue by matrix1001** [QData/TextAttack#445]
**Describe the bug**
As Title

**To Reproduce**
Steps to reproduce the behavior: (platform: win10, python3.6)
1. Run following command `textattack`
2. See error

**Screenshots or Traceback**
First bug
![image](https://user-images.githubusercontent.com/32097922/114352311-5188f400-9b9e-11eb-98d9-716e85282fa0.png)
Second bug
![image](https://user-images.githubusercontent.com/32097922/114352362-5d74b600-9b9e-11eb-8990-e8d3aaf56e97.png)

**Fix suggestion**
`shared\utils\install.py`
```python
......
def s3_url(uri):
    uri = uri.replace('\\', '/')
    return "https://textattack.s3.amazonaws.com/" + uri
......
def http_get(folder_name, out_file, proxies=None):
......
    req = requests.get(folder_s3_url, stream=True, proxies=proxies, verify=False)
......
```

**Comment by qiyanjun** [comment]
I believe this is solved..
