### ISSUE TITLE
Peek dataset command on dataset from file does not work

### ISSUE THREAD

**Issue by Ashiq5** [QData/TextAttack#447]
**Describe the bug**
Peek dataset command on custom dataset returns failure.

**To Reproduce**
Run following command `textattack peek-dataset --dataset-from-file <*.py>`

**Expected behavior**
Expected to see basic statistics about the custom dataset.

**Screenshots or Traceback**
![image](https://user-images.githubusercontent.com/14335681/114791501-a8d0c500-9d54-11eb-95bf-795cd17cfbff.png)

**System Information (please complete the following information):**
 - OS: Linux
 - Textattack version: Latest

**Comment by Ashiq5** [comment]
Linked #448.

**Comment by jxmorris12** [comment]
awesome @Ashiq5 - thank you!!!
