### ISSUE TITLE
Question about using custom dataset

### ISSUE THREAD

**Issue by LilyNLP** [QData/TextAttack#450]
I want to attack a custom dataset by using --dataset_from_file custom_dataset.py. Could you please indicate which form should the custom_dataset.py be like? Thank you!

**Comment by RishabhMaheshwary** [comment]
Hi, you can take a look at this #282.

**Comment by jxmorris12** [comment]
@RishabhMaheshwary thanks for the answer! Yep, @LilyNLP  -- the issue Rishabh referenced should explain how to format the file to pass via --dataset_from_file. Feel free to reopen the issue if you have more questions!
