### ISSUE TITLE
Words diff suggestion

### ISSUE THREAD

**Issue by matrix1001** [QData/TextAttack#451]
**Describe the bug**
![image](https://user-images.githubusercontent.com/32097922/115559424-48a6c980-a2e6-11eb-8e8e-f72d543aa3a4.png)

**To Reproduce**
Run following command `textattack attack --model cnn-ag-news --recipe textbugger --num-examples 10`

**Expected behavior**
As shown in the pic, the real `Average perturbed word %` should not reach that high. I found the reason in `attack_recipes/shared/attacked_text.py:line 234`.

```python
    def all_words_diff(self, other_attacked_text):
        """Returns the set of indices for which this and other_attacked_text
        have different words."""
        indices = set()
        w1 = self.words
        w2 = other_attacked_text.words
        for i in range(min(len(w1), len(w2))):
            if w1[i] != w2[i]:
                indices.add(i)
        return indices
```

Apparently this comparison according to the absolute position is not proper. I believe we can find another proper algorithm.

**Comment by qiyanjun** [comment]
this is solved by https://github.com/QData/TextAttack/pull/453
