### ISSUE TITLE
Question related to adversarial training

### ISSUE THREAD

**Issue by devvrit** [QData/TextAttack#457]
I'm not sure but are you guys making the model to eval() mode when attacking during adversarial training?
I looked at the code and possibly missed noticing that. So thought would double-check here.

Thanks,
Devvrit

**Comment by RishabhMaheshwary** [comment]
Yes, see [this](https://github.com/QData/TextAttack/blob/10309a32deb9b7daeafa3434b4a3bfea990f442b/textattack/commands/train_model/run_training.py#L476) in `run_training.py`.

**Comment by jxmorris12** [comment]
Hi @devvrit. Looks like the model is still in training mode when the adversarial examples are generated -- I'm looking at this file: https://github.com/QData/TextAttack/blob/master/textattack/commands/train_model/run_training.py

This decision is, at least, questionable – thanks for bringing it to our attention. We can discuss it further if you want. (The model is in eval mode when evaluated to get eval-set accuracy at the end of the training loop.)

**Comment by devvrit** [comment]
Hi @jxmorris12. Thanks for clarifying.
Yes, I believe it should be in eval mode when doing attacks. In the vision community too, that's what I've mostly observed. Moreover, the aim of the attacks is to generate perturbation that could fool the model at that point (whenever it's attacked). Hence the model should be in eval mode because that's how we'd be using it in practice if we were using the model trained till that point.

It'll also be great if one could test both the approaches over different datasets, compare results, and do some analysis :)

**Comment by jxmorris12** [comment]
agree @devvrit -- this is an interesting experimental question!
