### ISSUE TITLE
Query regarding Seq2sick attack

### ISSUE THREAD

**Issue by dsvrsec** [QData/TextAttack#472]
Hi,I am trying to run seq2sick on Machine Translation Pretrained transformer model (English to German) and also on custom pretrained model (English to Spaish).
There are some issues I find w.r.t pretrained model.
1.The attack is performed even the target translation(ground truth) is not the same as predicted translation.
Ex: deberias tenias que querias que querias que viniera solo .(Predicted Translation)--> deberias deberias haber rodeado de cosas que querias , yo solo .(adversarial Translation)

You should have **told** me that you wanted me to come alone.

You should have **asserted** me that you wanted me to come alone.

where as the actual ground truth prediction is "Debiste haberme dicho que querías que yo viniera solo."
But in the documentation ,it is provided that attack is skipped if the predicted output is not equal to ground truth output.Is there any reason for this.?

2.When I tried to run the command line of t5 model,I see that here also the attack is successful even if the Non Overlapping condition(Goal function) is not satisfied i.e. there are words like 'Und','ich','denke' overlapping at the same position of translated sentence.(This issue is there with custom model also)...

Ex: Und ich denke, dass dies unglaublich interessante Möglichkeiten für Technologen schaffen wird --> Und ich glaube, dass es einige unglaublich faszinierende Möglichkeiten für Technologen

And I **think** that &apos;s going to create some incredibly intriguing opportunities for technologists .

And I **believing** that &apos;s going to create some incredibly intriguing opportunities for technologists .

( textattack attack --model t5-en-de --recipe seq2sick --num-examples 100-I have used this command line)

**Can you please clarify on these issues.Thank you.**

**Comment by jxmorris12** [comment]
Hi @dsvrsec --

Looking at the [seq2sick attack recipe](https://github.com/QData/TextAttack/blob/master/textattack/attack_recipes/seq2sick_cheng_2018_blackbox.py), this recipe is using the [NonOverlappingOutput](https://github.com/QData/TextAttack/blob/9a67b9eff09a2b4382d3ecc0ddfe0afba5039162/textattack/goal_functions/text/non_overlapping_output.py#L17) goal function. So the algorithm in question is the word_difference_score() function in the linked file.

To answer your questions:

1. The attack will run until all the words are different from the ground truth output. So if they're all different to begin with, the attack will never run, and if only some of the words are different, the attack will run until every word is different from the ground truth.

This is probably not the best way to do this. In theory, we could only run the attack if the translation is perfect to begin with. I think this is what you're implying. However, I don't think that the model outputs a *perfect* translation almost ever.

2. What you're experiencing must be a bug in the word_difference_score(), but I'm not sure how it's happening. Hopefully we can track this down and fix it.

**Comment by dsvrsec** [comment]
Thank you for the reply. There is one issue with I am recently getting with custom model(I am not sure if it is due to updated code).
When I try to run the Attacker function (by following the notebooks in docs folder),I get this error.
`~\.conda\envs\tf_env2\lib\site-packages\textattack-0.2.16-py3.6.egg\textattack\goal_functions\text\text_to_text_goal_function.py in _process_model_outputs(self, _, outputs)
     23     def _process_model_outputs(self, _, outputs):
     24         """Processes and validates a list of model outputs."""
---> 25         return outputs.flatten()
     26 
     27     def _get_displayed_output(self, raw_output):

AttributeError: 'list' object has no attribute 'flatten'`

When I test with few inputs to custom wrapper,I get this ouput
`CustomKerasModelWrapper(model)(["ccccccccccccc is ","hi"])
Output: [['facil toque esta en casa .', 'hola']]
`
When I change the output to numpy array also,I get the error when I run Attacker as 
"not able to convert np.ndarray,need either of float,int...etc.".

Can you please any suggest any solution for this.Thank you

**Comment by srujanjoshi** [comment]
You can post the subsequent question/proposed resolution to the problem as a separate issue if you still having trouble with this problem.
