### ISSUE TITLE
is scipy==1.4.1 really neccessary?

### ISSUE THREAD

**Issue by XiYuan68** [QData/TextAttack#489]
**Is your feature request related to a problem? Please describe.**
I am trying to install textattack via pip but encountered a compiling error with scipy==1.4.1. I did some searches and found that many faced similar installation problems with this version of scipy. The current version of scipy I installed is 1.6.3 and it's working fine with many other adversarial attack toolbox such as foolbox, cleverhans and adversarial-robustness-toolbox, so I guess it will also work along with textattack?

**Describe the solution you'd like**
Replace scipy==1.4.1 with a higher version that isn't difficult to install

**Describe alternatives you've considered**
scipy==1.6.3

**Additional context**
I am not very familiar with different version of scipy but I guess avoiding scipy versions that require fortran compiler will provide a smoother installation.

**Comment by 425267211** [comment]
Here is the end of the scipy installation error:

```
  Warning: Unused variable ‘t5’ declared at (1) [-Wunused-variable]
  gfortran:f77: scipy/sparse/linalg/eigen/arpack/ARPACK/UTIL/dmout.f
  gfortran:f77: scipy/sparse/linalg/eigen/arpack/ARPACK/UTIL/zvout.f
  gfortran:f77: scipy/sparse/linalg/eigen/arpack/ARPACK/UTIL/svout.f
  gfortran:f77: /tmp/pip-install-tz13t6vv/scipy_0a7c17b420ce4c77a2b4a43bf54062fd/scipy/_build_utils/src/wrap_g77_abi_f.f
  error: Command "/usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops -Iscipy/sparse/linalg/eigen/arpack/ARPACK/SRC -I/usr/lib/python3.9/site-packages/numpy/core/include -Ibuild/src.linux-x86_64-3.9/numpy/distutils/include -c -c scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dsaup2.f -o build/temp.linux-x86_64-3.9/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dsaup2.o" failed with exit status 1
  
  ########### CLIB COMPILER OPTIMIZATION ###########
  Platform      :
    Architecture: x64
    Compiler    : gcc
  
  CPU baseline  :
    Requested   : 'min'
    Enabled     : SSE SSE2 SSE3
    Flags       : -msse -msse2 -msse3
    Extra checks: none
  
  CPU dispatch  :
    Requested   : 'max -xop -fma4'
    Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_KNM AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
    Generated   : none
  CCompilerOpt._cache_write[796] : write cache to path -> /tmp/pip-install-tz13t6vv/scipy_0a7c17b420ce4c77a2b4a43bf54062fd/build/temp.linux-x86_64-3.9/ccompiler_opt_cache_clib.py
  ----------------------------------------
  ERROR: Failed building wheel for scipy
Failed to build scipy
ERROR: Could not build wheels for scipy which use PEP 517 and cannot be installed directly
```

I know you guys are not responsible for a scipy installation error but switching to a more popular version with less problem can always make people easier to try your good work.

**Comment by qiyanjun** [comment]
0. For many of the dependent library issues, the following command is the first you could try:

pip install --force-reinstall textattack
Besides, we highly recommend you to use virtual environment for textattack use, see information here. Here is one conda example:

conda create -n textattackenv python=3.7
conda activate textattackenv
conda env list

**Comment by XiYuan68** [comment]
No, `pip install --force-reinstall textattack` doesn't work

Yes, I know using virtual environment is a work-around, but it kinda stops people from trying your toolbox when other adversarial attack toolbox can be more easily installed, especially if there is no obvious reasons to hang on the specific old version of scipy.

**Comment by qiyanjun** [comment]
Thanks.. please see https://github.com/QData/TextAttack/pull/490

**Comment by XiYuan68** [comment]
Thank you for responding so fast! I'll try textattack on my project ASAP!
