### ISSUE TITLE
method _text_index_of_word_index of AttackedText has bugs

### ISSUE THREAD

**Issue by wenh06** [QData/TextAttack#526]
**Describe the bug**
the searching range from the second (index from 1) word in the `pre_words` is not correct, which includes its previous word. If the current word is a substring of its previous word, then error comes. This can be clearly illustrated in the forthcoming example.

**To Reproduce**
1. Run following command `textattack ...`
2. Run following code ...

```python
at = AttackedText("Flamboyant in some movies and artfully restrained in others, 65-year-old Jack Nicholson could be looking at his 12th Oscar nomination by proving that he's now, more than ever, choosing his roles with the precision of the insurance actuary")
at.text_window_around_index(5, 5)
```
The outcome is `movies and artfully restrain`, which should be `movies and artfully restrained in`. `in` is a substring of `restrained` which causes the bug. The solution is to replace the function `_text_index_of_word_index` by the following:

```python
def _text_index_of_word_index(self, i):
    """Returns the index of word ``i`` in self.text."""
    pre_words = self.words[: i + 1]
    lower_text = self.text.lower()
    # Find all words until `i` in string.
    look_after_index = 0
    for word in pre_words:
        look_after_index = lower_text.find(word.lower(), look_after_index) + len(word)
    look_after_index -= len(self.words[word_idx])
    return look_after_index
```

**Expected behavior**
ref. the previous section

**Screenshots or Traceback**
NA

**System Information (please complete the following information):**
 - OS: [e.g. MacOS, Linux, Windows]
 - Library versions (e.g. `torch==1.7.0, transformers==3.3.0`)
 - Textattack version
 NA

**Additional context**
I've found several bugs in the AttackedText. It is the most fundamental class (util) in the whole project. I suggest do more test on this class.

The orignal example is ``Flamboyant in some movies and artfully restrained in others, 65-year-old Jack Nicholson could be looking at his 12th Oscar nomination by proving that he's now, more than ever, choosing his roles with the precision of the insurance actuary.`` from `SST`

Raw texts from `SST` seem to have spaces before punctuations which potentially cause bugs (e.g. `...he 's now...`). I suggest use the following for preprocessing

```python
import re
from string import punctuation

def remove_space_before_punct(text:str) -> str:
    """
    """
    pattern = f"\s[{punctuation}]"
    start = 0
    res = ""
    for item in re.finditer(pattern, text):
        res += (text[start:item.start()] + re.sub("\s", "", item.group()))
        start = item.end()
    res += text[start:]
    return res
```

The function `words_from_text` can also be rewritten using `re`

```python
def words_from_text(s:str, words_to_ignore:list=[]) -> list:
    """
    """
    homos = "ɑЬϲԁе𝚏ɡհіϳ𝒌ⅼｍոорԛⲅѕ𝚝սѵԝ×уᴢ"
    exceptions = "'-_*@"
    filter_pattern = "|".join(homos)+"|'|\-|_|\*|@"
    filter_pattern = f"[\w|{filter_pattern}]+"
    words = []
    for word in s.split():
        # Allow apostrophes, hyphens, underscores, asterisks and at signs as long as they don't begin the word.
        word = word.lstrip(exceptions)
        filt = [w.lstrip(exceptions) for w in re.findall(filter_pattern, word)]
        words.extend(filt)
    words = list(filter(lambda w: w not in words_to_ignore+[""], words))
    return words
```

**Comment by jxmorris12** [comment]
Thanks for the comments @wenh06 - I agree this is a big deal and should be fixed! The edge case you proposed ('in' as a substring of 'restrained') makes sense.

Can you propose a PR that fixes this bug? I'll review it myself (just tag me or add me as a reviewer).

>I've found several bugs in the AttackedText. 

this bug is critical, and I hope we fix it soon. Luckily, it only affects a very small subset of typical input data. Please let us know if there are any other bugs that we can fix too

**Comment by wenh06** [comment]
> Thanks for the comments @wenh06 - I agree this is a big deal and should be fixed! The edge case you proposed ('in' as a substring of 'restrained') makes sense.
> 
> Can you propose a PR that fixes this bug? I'll review it myself (just tag me or add me as a reviewer).
> 
> > I've found several bugs in the AttackedText.
> 
> this bug is critical, and I hope we fix it soon. Luckily, it only affects a very small subset of typical input data. Please let us know if there are any other bugs that we can fix too

OK. I still have one pending PR #509. Can I make multiple PRs?

Another thing is that, I think over again about my `remove_space_before_punct` that it better not be used currently because of possible existence of quotations, for example `I like the film "The Lord of the Rings"`

**Comment by wenh06** [comment]
PR was merged, hence this issue should be closed.
