### ISSUE TITLE
Difference between Failed and Skipped Attack

### ISSUE THREAD

**Issue by SJabin** [QData/TextAttack#527]
Hi,

First of all, kudos to TextAttack for such a neat implementation of the adversarial attacks. 

I was looking through the docs to understand the difference between the  Failed and Skipped attack but couldn't understand it quite yet. For example, below are the two results from the [TextAttack & AllenNLP](https://textattack.readthedocs.io/en/latest/2notebook/Example_2_allennlp.html#TextAttack-&-AllenNLP) page:

--------------------------------------------- Result 3 ---------------------------------------------
Positive (100%) --> [FAILED]
that loves its characters and communicates something rather beautiful about human nature

--------------------------------------------- Result 4 ---------------------------------------------
Positive (82%) --> [SKIPPED]
remains utterly satisfied to remain the same throughout

One is failed, and the other is skipped. What does it mean? When a sentence is skipped and when the attack is considered to be failed?

Many thanks!

**Comment by qiyanjun** [comment]
@Hanyu-Liu-123 can you take a look at this?

**Comment by Hanyu-Liu-123** [comment]
Hi Sjabin, thank you for your interest in TextAttack!

During an attack, a class named `GoalFunction` is called to to evaluate how well a perturbed attacked_text object is in achieving a specific goal. The list of goal functions that TextAttack implements can be found [here](https://github.com/QData/TextAttack/tree/master/textattack/goal_functions).

Specifically, how each goal function assigns SKIPPED, FAILED, and SUCCESS different from one another, so it's difficult to give a defined answer to when a sentence is skipped and when the attack is considered to be failed. The function that assigns results in the super class can be found [here](https://github.com/QData/TextAttack/blob/7d2de08771d6e1125e391d103ede43bfdaf88a62/textattack/goal_functions/goal_function.py#L109), and if you look into the subclasses of `GoalFunction` you'll be able to learn more about how SKIPPED and FAILED are assigned for each specific goal function.

Hope this answers your question!

**Comment by SJabin** [comment]
Thank you very much for the clarification. @Hanyu-Liu-123. Appreciate it.

**Comment by qiyanjun** [comment]
@Hanyu-Liu-123 thanks
