### ISSUE TITLE
Extra character to substituted words when running CLAREAugmenter

### ISSUE THREAD

**Issue by Hanyu-Liu-123** [QData/TextAttack#538]
**Describe the bug**
When the CLAREAugmenter substitutes a word, there's an extra character that is added to the front (Ġ). The CLARE transformation method should remove that extra character before the transformed text is returned by the transformation.

**To Reproduce**
```
from textattack.augmentation import CLAREAugmenter
s = 'What I cannot create, I do not understand.'
augmenter = CLAREAugmenter()
augmenter.augment(s)
```
**Expected behavior**
`['What I cannot create, I do sometimes not understand.']`

**Actual behaviorr**
`['What I cannot create, I do Ġsometimes not understand.']`

**Comment by qiyanjun** [comment]
This is what I get running the same code: 

['What Ġmistakes I cannot create, I do not understand.']
