### ISSUE TITLE
Search method of the DeepWordBug recipe might should be adjusted

### ISSUE THREAD

**Issue by wenh06** [QData/TextAttack#549]
The [search method](https://github.com/QData/TextAttack/blob/18111055c44308fd05159ff72b02dc2eccfb2276/textattack/attack_recipes/deepwordbug_gao_2018.py#L77) of the `DeepWordBug` recipe is [`GreedyWordSwapWIR`](https://github.com/QData/TextAttack/blob/18111055c44308fd05159ff72b02dc2eccfb2276/textattack/search_methods/greedy_word_swap_wir.py#L25) WITHOUT specifying its `wir_method`. The default `wir_method` for `GreedyWordSwapWIR` is `unk` which replaces the word with an `oov` word or token for computation of importance score or something like that. However, in the [paper](https://ieeexplore.ieee.org/document/8424632) which introduces the `DeepWordBug` recipe, in page 3 (page 52) starting from the 8th line of the right column, it is stated that
```
Therefore, we directly measure ΔiF(x) by removing the ith word. Comparing the prediction before and after a word is removed reflects how the word influences the classification result.
```

So, should [this line](https://github.com/QData/TextAttack/blob/18111055c44308fd05159ff72b02dc2eccfb2276/textattack/attack_recipes/deepwordbug_gao_2018.py#L77)
```python
search_method = GreedyWordSwapWIR()
```
be replaced with
```python
search_method = GreedyWordSwapWIR(wir_method="delete")
```
? Thank you very much!

**Comment by qiyanjun** [comment]
@wenh06 thanks for the question. In the deepWordBug code, the default was to replace with OOV..We implemented the recipe following the original code setup.
