### ISSUE TITLE
Attacking a Hate Speech Detection Model

### ISSUE THREAD

**Issue by marwanomar1** [QData/TextAttack#557]
I am trying to run an attack on a pretrained, fine-tuned model as follows:
!textattack attack --model cardiffnlp/twitter-roberta-base-offensive --recipe deepwordbug --num-examples 10

but its giving me the following error:
ValueError: Must supply pretrained model or dataset

I am not sure why it would not take the pretrained model above- is there anything I am doing wrong here?

@jxmorris12

**Comment by DavidHerel** [comment]
@marwanomar1 could you please provide me a code, which have worked for you? I have the same problem

**Comment by jxmorris12** [comment]
@DavidHerel are you getting the same error message? Maybe you need to supply a dataset
