### ISSUE TITLE
Mismatch config filename for LSTM and CNN pretrained models

### ISSUE THREAD

**Issue by dangne** [QData/TextAttack#561]
**Describe the bug**

When loading CNN (with [`.from_pretrained()`](https://github.com/QData/TextAttack/blob/1918bfd1e3e7c015ee7fe717f10086f7007116c3/textattack/models/helpers/word_cnn_for_classification.py#L86)) or LSTM (with [`.from_pretrained()`](https://github.com/QData/TextAttack/blob/1918bfd1e3e7c015ee7fe717f10086f7007116c3/textattack/models/helpers/lstm_for_classification.py#L100)), the code looks for a config file named `config.json` inside the model directory. If the file does not exist, then the default config is used. However, I found that for `lstm-ag-news` and `cnn-ag-news`, the config is named  `train_args.json` so when loading those models, `config.json` is not found and the default config is used, which results in the error I show in the screenshot below. This is due to the default config having `num_labels=2` while `lstm-ag-news` and `cnn-ag-news` have `num_labels=4`.

I have only checked this on the AG's news but other datasets may have this issue as well.

**Expected behavior**
The config filename must match with the code, and therefore, should be found.

**Screenshots or Traceback**
![image](https://user-images.githubusercontent.com/36122564/139575503-71c8377e-3c0e-4ea7-848f-b16a547c34b8.png)

**System Information (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - Textattack version 0.3.0

**Comment by dangne** [comment]
Another error is that the `train_args.json` of CNN and LSTM don't have the "architectures" key which will raise a KeyError at https://github.com/QData/TextAttack/blob/1918bfd1e3e7c015ee7fe717f10086f7007116c3/textattack/models/helpers/word_cnn_for_classification.py#L115
https://github.com/QData/TextAttack/blob/1918bfd1e3e7c015ee7fe717f10086f7007116c3/textattack/models/helpers/lstm_for_classification.py#L131

**Comment by srujanjoshi** [comment]
With the Latest Version of TextAttack (installed from Source), I am unable to reproduce this issue,
OS: Ubuntu 20.04.3 LTS 

This is the output that the provided code snippets produce:
![Screenshot from 2021-11-03 15-12-14](https://user-images.githubusercontent.com/44235961/140177853-dbeb3be9-4bb3-467e-b474-cb4bf0d41bcf.png)
![Screenshot from 2021-11-03 15-15-35](https://user-images.githubusercontent.com/44235961/140177889-648b56cf-a616-4d98-aea5-608a7b4d6436.png)
