### ISSUE TITLE
Minor typos in the Model zoo docs

### ISSUE THREAD

**Issue by khieu** [QData/TextAttack#564]
**Describe the bug**
In the model zoo documentations, for the semantic similarity pretrained model, there is a consistent typo. Instead of `paraphrase`, the documents use the term `paraphase` which I think is not correct.

**To Reproduce**
in page such as:
https://textattack.readthedocs.io/en/latest/3recipes/models.html
search page for `paraphase`

**Expected behavior**
Should be spelled `paraphrase`

**Comment by srujanjoshi** [comment]
#575 fixes the minor typo mentioned.
