### ISSUE TITLE
AssertionError: Got 6 outputs for 1 inputs

### ISSUE THREAD

**Issue by bdubbs09** [QData/TextAttack#566]
I trained a TFHub and Keras model on IMDB, then created a custom dataset to attack. Using 10 examples in the dataset, the TFHub model worked well attacking, but the Keras model fails to attack throwing the following trace:

`---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-12-abd29780a849> in <module>
      3 attack_args = AttackArgs(num_examples=10)
      4 attacker = Attacker(keras_attack, dataset, attack_args)
----> 5 attacker.attack_dataset()

~\textattack\textattack\attacker.py in attack_dataset(self)
    439             self._attack_parallel()
    440         else:
--> 441             self._attack()
    442 
    443         if self.attack_args.silent:

~\textattack\textattack\attacker.py in _attack(self)
    168                 result = self.attack.attack(example, ground_truth_output)
    169             except Exception as e:
--> 170                 raise e
    171             if (
    172                 isinstance(result, SkippedAttackResult) and self.attack_args.attack_n

~\textattack\textattack\attacker.py in _attack(self)
    166                 example.attack_attrs["label_names"] = self.dataset.label_names
    167             try:
--> 168                 result = self.attack.attack(example, ground_truth_output)
    169             except Exception as e:
    170                 raise e

~\textattack\textattack\attack.py in attack(self, example, ground_truth_output)
    414             ground_truth_output, (int, str)
    415         ), "`ground_truth_output` must either be `str` or `int`."
--> 416         goal_function_result, _ = self.goal_function.init_attack_example(
    417             example, ground_truth_output
    418         )

~\textattack\textattack\goal_functions\goal_function.py in init_attack_example(self, attacked_text, ground_truth_output)
     59         self.ground_truth_output = ground_truth_output
     60         self.num_queries = 0
---> 61         result, _ = self.get_result(attacked_text, check_skip=True)
     62         return result, _
     63 

~\textattack\textattack\goal_functions\goal_function.py in get_result(self, attacked_text, **kwargs)
     70         """A helper method that queries ``self.get_results`` with a single
     71         ``AttackedText`` object."""
---> 72         results, search_over = self.get_results([attacked_text], **kwargs)
     73         result = results[0] if len(results) else None
     74         return result, search_over

~\textattack\textattack\goal_functions\goal_function.py in get_results(self, attacked_text_list, check_skip)
     87             attacked_text_list = attacked_text_list[:queries_left]
     88         self.num_queries += len(attacked_text_list)
---> 89         model_outputs = self._call_model(attacked_text_list)
     90         for attacked_text, raw_output in zip(attacked_text_list, model_outputs):
     91             displayed_output = self._get_displayed_output(raw_output)

~\textattack\textattack\goal_functions\goal_function.py in _call_model(self, attacked_text_list)
    207                 if text not in self._call_model_cache
    208             ]
--> 209             outputs = self._call_model_uncached(uncached_list)
    210             for text, output in zip(uncached_list, outputs):
    211                 self._call_model_cache[text] = output

~\textattack\textattack\goal_functions\goal_function.py in _call_model_uncached(self, attacked_text_list)
    178             outputs = torch.cat(outputs, dim=0)
    179 
--> 180         assert len(inputs) == len(
    181             outputs
    182         ), f"Got {len(outputs)} outputs for {len(inputs)} inputs"

AssertionError: Got 6 outputs for 1 inputs`

For reference, I'm using the PWWSRen2019 attack recipe and this is the dataset that I'm attacking:
`data = [("I enjoyed the movie a lot!", 1), 
        ("Absolutely horrible film.", 0), 
        ("Our family had a fun time!", 1),
        ("The movie wasn't very interesting at all", 0),
        ("We really enjoyed the theater!", 1),
        ("The popcorn was terrible!", 0),
        ("Great seats and great film!",1),
        ("The family really didn't enjoy the show at all.", 0),
        ("I definitely recommend this movie!", 1),
        ("I hated everything about the movie.", `1)]`

Any help would be appreciated.

**Comment by jxmorris12** [comment]
This is a pretty informative error message actually. It looks like your model isn't returning the expected shape of values. What does your model wrapper look like?

**Comment by bdubbs09** [comment]
> This is a pretty informative error message actually. It looks like your model isn't returning the expected shape of values. What does your model wrapper look like?

`class CustomKerasModelWrapper(ModelWrapper):
    def __init__(self, model):
        self.model = model
        
    def __call__(self, text_input_list):
        # These two variables are unique to this problem
        num_words = 1000
        vocabulary = tf.keras.datasets.imdb.get_word_index(path='imdb_word_index.json')
        
        x_transform = []
        for i, review in enumerate(text_input_list):
            tokens = [x.strip(",") for x in review.split()]
            BoW_array = np.zeros((num_words,))
            for word in tokens:
                if word in vocabulary:
                    if vocabulary[word] < len(BoW_array):
                        BoW_array[vocabulary[word]] += 1
                x_transform.append(BoW_array)
        x_transform = np.array(x_transform)
        prediction = self.model.predict(x_transform)
        return prediction`

This was pulled from their examples in the docs, which may or may not be correct. Their example was through the Rotten Tomatoes dataset, which is pretty much the same as the one that I created as a custom dataset. Its also the same model that was initially created in the "Attack Custom Keras Model" portion of the guide.

**Comment by jxmorris12** [comment]
Hi @bdubbs09 - I don't know the specifics of this model but I still think it's returning the wrong shape of things. I think it's supposed to be prediction scores for each class, for each input, so if text_input_list is a list of 3 sentences, this __call__ method should return an np array of shape [3, 2] where each row is a list of probabilities that sums to one. So a sample output in that case would be `[[0.95, 0.05], [0.3, 0.7], [0.44, 0.56]]`. Can you make sure your model wrapper is returning output of shape `[len(text_input_list), 2]`?
