### ISSUE TITLE
apidocs have disappeared?

### ISSUE THREAD

**Issue by stroypet** [QData/TextAttack#568]
**Describe the bug**
apidocs on readthedocs have disappeared for certain pages

**To Reproduce**
1. https://textattack.readthedocs.io/en/latest/apidoc/textattack.html < - navigate here

**Expected behavior**
There is text here describing things.

**Screenshots or Traceback**
![image](https://user-images.githubusercontent.com/6641202/140948128-5e466d75-291d-44f0-8f7f-60701179faa2.png)

![image](https://user-images.githubusercontent.com/6641202/140948191-c4abe645-98d6-4bbe-a831-e4d940e8656a.png)

**System Information (please complete the following information):**
N/A

**Comment by qiyanjun** [comment]
https://github.com/QData/TextAttack/pull/570
