### ISSUE TITLE
Cannot use textattack (import not working)

### ISSUE THREAD

**Issue by 25icecreamflavors** [QData/TextAttack#584]
**Describe the bug**
I try to use this library and start with importing it. But it says "ImportError: cannot import name 'FailedAttackResult' from 'textattack.attack_results' (/opt/conda/lib/python3.7/site-packages/textattack/attack_results/__init__.py)"

**To Reproduce**
1. Run following command `!pip install textattack`
2. Run following code `import textattack`

 - Textattack version 0.3.4

**Additional context**
I also tried to use version 0.3.3 and install tensorflow_text additionally, but it doesn't help.

**Comment by qiyanjun** [comment]
mind to share with us some details on your OS? terminal? 

https://textattack.readthedocs.io/en/master/0_get_started/installation.html''

**Comment by 25icecreamflavors** [comment]
I'm not sure about OS, I tried to use this library in kaggle notebooks.

**Comment by zloelias** [comment]
Google Colab
Python 3.7.12 (default, Sep 10 2021, 00:21:48) 
[GCC 7.5.0] on linux

import textattack

`AttributeError                            Traceback (most recent call last)
<ipython-input-11-be23297719a4> in <module>()
----> 1 import textattack.shared

1 frames
/usr/local/lib/python3.7/dist-packages/textattack/__init__.py in <module>()
     17 from .attack import Attack
     18 from .attacker import Attacker
---> 19 from .trainer import Trainer
     20 
     21 from . import (

/usr/local/lib/python3.7/dist-packages/textattack/trainer.py in <module>()
     21 from .training_args import CommandLineTrainingArgs, TrainingArgs
     22 
---> 23 logger = textattack.shared.logger
     24 
     25 

AttributeError: module 'textattack' has no attribute 'shared'`

**Comment by donggrant** [comment]
We had this issue earlier. The no "shared" attribute should be resolved if you run `!pip install textattack['tensorflow']` instead of just `!pip install textattack`.

**Comment by IS5882** [comment]
I also get this error when I _`!pip install textattack[tensorflow,optional]`_
 and  ` import textattack` on **Kaggle Notebook GPU backend** I get this error `FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/lib/python3.7/site-packages/six-1.16.0.dist-info/METADATA'`
 
When I try this instead:
`!pip install textattack['tensorflow']
`
I get this error when I import textattack:
`ImportError: cannot import name 'FailedAttackResult' from 'textattack.attack_results' (/opt/conda/lib/python3.7/site-packages/textattack/attack_results/__init__.py)`
