### ISSUE TITLE
Broken loading datasets from huggingface-hub

### ISSUE THREAD

**Issue by zloelias** [QData/TextAttack#590]
TextAttack 0.3.0 downgrade datasets module to datasets-1.2.1
And this brake downloading from huggingface-hub personal repo 

**To Reproduce**
`! pip install textattack=="0.3.0"`
`from textattack.datasets import HuggingFaceDataset`
`dataset_name = 'zloelias/lenta-ru'
dataset = HuggingFaceDataset(dataset_name, None, 'test', dataset_columns=(['text'], 'labels'))`

FileNotFoundError: Couldn't find file locally at zloelias/lenta-ru/lenta-ru.py, or remotely at https://raw.githubusercontent.com/huggingface/datasets/1.2.1/datasets/zloelias/lenta-ru/lenta-ru.py or https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/zloelias/lenta-ru/lenta-ru.py.
If the dataset was added recently, you may need to to pass script_version="master" to find the loading script on the master branch.

**Expected behavior**
Download dataset

**Screenshots or Traceback**
If applicable, add screenshots to help explain your problem. Also, copy and paste tracebacks produced by the bug. 

**System Information (please complete the following information):**
 - OS: google colab, linux, Python 3.7.12
 - Library versions (e.g. `torch==1.7.0, transformers==3.3.0`)
 - Textattack version 0.3.0

**Additional context**
Upgrading datasets version after installing textattack works fine
`! pip install textattack=="0.3.0"`
`! pip install datasets --upgrade`
`from textattack.datasets import HuggingFaceDataset`
`dataset_name = 'zloelias/lenta-ru'
dataset = HuggingFaceDataset(dataset_name, None, 'test', dataset_columns=(['text'], 'labels'))`

**Comment by qiyanjun** [comment]
@donggrant please help?
