### ISSUE TITLE
Installation on Apple Silicon 🍎

### ISSUE THREAD

**Issue by srujanjoshi** [QData/TextAttack#594]
# Installation on Apple Silicon 🍎 

This is a guide to install TextAttack on Machines which use Apple Silicon CPUs/GPUs. This guide is for running TextAttack natively on the underlying ARM architecture and not through Rosetta 2 translation. 

NOTE: All of the features of TextAttack have not been thoroughly tested on Apple Silicon and there may be some issues. This guide has been written with the latest version of TextAttack (at the time of writing) in mind. Future versions of TextAttack may have additional dependencies which could require changes to the instructions below. 

# Why can't I directly install TextAttack on Apple Silicon?

Apple's new line of Macs ditches Intel's CPUs in favor of Apple's own Apple Silicon CPUs. Apple Silicon CPUs use ARM architecture instead of x86 architecture. A drawback of this for us is that a lot of Python Libraries (ML libraries in particular) contain code which is compiled for the x86 architecture.

The issue with directly installing the TextAttack package hosted on PyPI is that it has some dependencies for which pip cannot build ARM compatible wheels, and thus pip is unable to complete the installation. The reason for this is that some Python Packages are just Pythonic wrappers for C/C++ code that has been pre-compiled as x86 binaries. Such packages will need to be compiled locally to produce ARM binaries in order to be installed on Apple Silicon. 

Furthermore, the default Tensorflow package hosted on PyPI is not optimized to run on Apple Silicon CPU/GPUs. 

NOTE: At the time of writing, PyTorch does not support Apple Silicon yet. See Issue: https://github.com/pytorch/pytorch/issues/47702

# Procedure 
So here are the overall steps to get TextAttack up and running: 

1. Install tensorflow
2. Install tokenizers 
3. Install Miscellaneous Dependencies
4. Install sentencepiece
5. Install h5py
6. Install tensorflow_text (and tensorflow again)
7. Install textattack

Make sure that the following steps are done in a Terminal running native ARM.

You can verify this by running the following command: 

```
arch
```

This should output `arm64`

## 0. Install HomeBrew 

[Homebrew](https://brew.sh) is a package manager for macOS that makes it a lot easier to install applications through the command line. Installing Homebrew is a prerequisite for the steps that follow. 

```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

## 1. Install Tensorflow

Apple has released the tensorflow-metal plugin which enables Tensorflow GPU acceleration on Apple Silicon. For more details visit: https://developer.apple.com/metal/tensorflow-plugin/

Download and Install Conda env: 

```
chmod +x ~/Downloads/Miniforge3-MacOSX-arm64.sh
sh ~/Downloads/Miniforge3-MacOSX-arm64.sh
source ~/miniforge3/bin/activate
```

The steps beyond this point are recommended to be done in the specific conda environment that you plan to use for TextAttack. 
You can create and activate a conda env like so: 

```
conda create -n textattackenv python 
conda activate textattackenv
```

Install Tensorflow Dependencies:

```
conda install -c apple tensorflow-deps
```
Install Base Tensorflow:

```
python -m pip install tensorflow-macos
```

Install tensor flow-metal plugin:

```
python -m pip install tensorflow-metal
```

## 2. Install Tokenizers

We have to build Tokenizers from source to ensure compatibility.  

In order to do this we need to have [Rust](https://www.rust-lang.org/tools/install) installed. 

```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

You can configure the current shell using the instructions in the command prompt after installation, or close and re-open the shell to continue. 

Once we have Rust, we can download the source code for tokenizers

```
git clone https://github.com/huggingface/tokenizers
```

Go to the Python Bindings Folder:

```
cd tokenizers/bindings/python
```

We need the following module to compile Rust within a Python Package:

```
pip install setuptools_rust
```

Finally, locally compile and install Tokenizers with the following command: 
```
python setup.py install
```

## 3. Install Miscellaneous Dependencies

Install the following dependencies manually using pip: 

```
pip install lru-dict gensim lxml xxhash
```

## 4. Install sentencepiece 

[sentencepiece](https://github.com/google/sentencepiece) mainly consists of C++ code with a Python wrapper. 
In order to build sentencepiece from the C++ source code we need the following additional tools:

1. [cmake](https://cmake.org)
2. C++11 compiler 
3. [gperftools](https://github.com/gperftools/gperftools)

XCode comes with a C++11 compiler called clang, so here is how we install the remaining components: 

```
brew install cmake pkg-config libgoogle-perftools-dev
```

Build the C++ source code: 

```
git clone https://github.com/google/sentencepiece.git 
cd sentencepiece
mkdir build
cd build
cmake ..
make -j $(nproc)
sudo make install
```

Now, navigate to sentencepiece/python and run the following commands:

```
python setup.py build
sudo python setup.py install
```

If you get an error about "Missing Write Access" to a Python Libraries folder, change the user permissions of that folder with  the following command: `sudo chown -R $USER <directory_name>` and rerun the failing command.

## 5. Install h5py 

The h5py package is a Pythonic interface to the HDF5 binary data format, which is used by Tensorflow and Tensorflow Text.

Install it like so:

```
conda install h5py
```

## 6. Install Tensorflow Text (and Tensorflow again)

Tensorflow Text is one the primary libraries that TextAttack depends on. At the time of writing, the PyPI package for Tensorflow Text does not support Apple Silicon natively, but Tensorflow Text can be built from the source to work with Apple Silicon. See: https://github.com/tensorflow/text/pull/756

However in order to do so, Tensorflow itself needs to be built from the source (along with Tensorflow Addons and Tensorflow IO)

For the sake of brevity, the code to do so will not be shown here. Linked [here](https://gist.github.com/TeoZosa/da88a858ad73a18e3f7410c4b615466d#file-m1-mac-source-builds-mecab_python3-tensorflow-tf_io-tf_addons-tf_text-sh) is a shell script which when run, builds Tensorflow, Tensorflow IO, Tensorflow Addons and Tensorflow Text from source, and produces wheels which can be used to install the aformentioned packages. 

NOTE: The script mentioned above will take a while to execute. It took around an hour and half to run on my M1 MacBook Pro. 

After running the shell script, the packages for Tensorflow, Tensorflow IO, Tensorflow Addons and Tensorflow Text will have been built locally. 

In the directory in which the script was ran, navigate to `packages/source_builds`, and run the following command to install all of the packages that were just built: 

```
pip install tensorflow-2.7.0-cp39-cp39-macosx_11_0_arm64.whl tensorflow_addons-0.15.0-cp39-cp39-macosx_11_0_arm64.whl tensorflow_io_gcs_filesystem-0.22.0-cp39-cp39-macosx_11_0_arm64.whl tensorflow_text-2.7.3-cp39-cp39-macosx_11_0_arm64.whl

```

## 7. Install TextAttack 

Once all of the previous steps have been completed, the following command should successfully install TextAttack:

```
pip install textattack
```

Cheers!

**Comment by qiyanjun** [comment]
This is excellent!

**Comment by jxmorris12** [comment]
Thanks @srujanjoshi - can you cross-post this into Discussions?

**Comment by jxmorris12** [comment]
@srujanjoshi, do you mind updating your instructions to include @gibfahn's recommendation?
