### ISSUE TITLE
Unsupported dataset schema for SQuAD

### ISSUE THREAD

**Issue by jw-dong** [QData/TextAttack#597]
I noticed that there was a closed issue [#529](https://github.com/QData/TextAttack/issues/529) that described the same problem with using textattack.datasets loading SQuAD. However, I followed the instruction there within as below, 

```
from textattack.datasets import HuggingFaceDataset
train_dataset = HuggingFaceDataset('squad', split='train')
eval_dataset = HuggingFaceDataset('squad', split='validation')
```

The problem seems persist. I still see the following error message, 

> ValueError: Unsupported dataset schema {'context', 'question', 'title', 'id', 'answers'}. Try passing your own `dataset_columns` argument.

**Comment by qiyanjun** [comment]
@jw-dong thanks for pointing this out. Mind to submit a PR to fix this?
