### ISSUE TITLE
How to load custom model using python interface? 

### ISSUE THREAD

**Issue by bl4bl4hhh** [QData/TextAttack#598]
The document only said that I can load the model using command-line interface:
"To experiment with a model you've trained, you could create the following file and name it my_model.py. Then, run an attack with the argument --model-from-file my_model.py. The model and tokenizer will be loaded automatically."
And I am using textattack 0.2.10

**Comment by qiyanjun** [comment]
see tutorials like; https://textattack.readthedocs.io/en/master/2notebook/Example_0_tensorflow.html
