### ISSUE TITLE
Help in SavedModel file does not exist at

### ISSUE THREAD

**Issue by Jebrankhan** [QData/TextAttack#606]
Hello
Can anyone please help me with the following error while using textattack. I have installed the textattack and it is working fine with deepwordbug attack, however when I want to generate other type of attacks like textfooler etc., it generates the following error.

OSError: SavedModel file does not exist at: C:\Users\HP1\AppData\Local\Temp\tfhub_modules\063d866c06683311b44b4992fd46003be952409c\{saved_model.pbtxt|saved_model.pb}

I am using the following command:
textattack attack --recipe textfooler --model bert-base-uncased-yelp --num-examples 1000 --log-to-csv D:\Colliboration\Results\AG\Textfool-yelp.csv --disable-stdout

**Comment by LalitWagh** [comment]
did you solved it? I am also having the same error.

**Comment by qiyanjun** [comment]
@cogeid can you help?

**Comment by LalitWagh** [comment]
Clear your desktop cache. it will work
try windows key + r, 
type %temp% select all and delete
type again temp and select all delete.
I am sure it will work. alteast worked for me.

**Comment by jxmorris12** [comment]
Sounds like this is a Windows-specific Tensorflow cache error. Thanks @LalitWagh for suggesting a fix. If someone else comes across this error, there's a good page in the TensorFlow issues where lots of people have discussed it: https://github.com/tensorflow/tensorflow/issues/22480
