### ISSUE TITLE
want Result table by running code instead on command prompt

### ISSUE THREAD

**Issue by LalitWagh** [QData/TextAttack#615]
So, Running attack on cmd returns table of results. Is there any way like how can we get that table in coding output? Please help.

**Comment by Hanyu-Liu-123** [comment]
Hi @LalitWagh, please try out this [notebook](https://github.com/QData/TextAttack/blob/master/docs/2notebook/1_Introduction_and_Transformations.ipynb) that provides instructions in running attacks.

**Comment by LalitWagh** [comment]
Hey there, 
I have gone through the resource you shared. I was asking about the results table we generate at the end of attack how can i save it in csv or what resource u will suggest.
