### ISSUE TITLE
Can we perform textattack on bigdata?

### ISSUE THREAD

**Issue by LalitWagh** [QData/TextAttack#616]
After evaluating and reading docs, i cant find any way to do the attacks on larger datasets that we will be fetching from database server. and the dataset needs to be converted before attacking which is very hard to implement. Any solution of example notebook can you create to solve this?

**Comment by Hanyu-Liu-123** [comment]
Hi @LalitWagh, the dataset class that TextAttack attacker uses is implemented [here](https://github.com/QData/TextAttack/blob/master/textattack/datasets/dataset.py), and it provides a short example of creating your own dataset. This [notebook](https://github.com/QData/TextAttack/blob/master/docs/2notebook/4_Custom_Datasets_Word_Embedding.ipynb) also introduces the process of using your dataset for attacks.

Thanks!

**Comment by LalitWagh** [comment]
So, I read the notebook. It helped me understand that we need the dataset on ordered dictionary in order to use textattack. Adding to my question, in aws server i have data but it has nearly 37 million rows and i dont want to convert it to ordered dictionary. So what solution can you propose for this problem?
Your any type of help is highly appreciated

**Comment by Hanyu-Liu-123** [comment]
Hi @LalitWagh, I think with our current implementation the only two ways to prepare a dataset is to download one from huggingface or create one from scratch (using an ordered dict as you suggest). I couldn't think of a way to directly use your own data without changing the dataset class. I'll leave this issue open to see if others have any suggestions.

**Comment by jxmorris12** [comment]
@LalitWagh the datasets HuggingFace supports are backed by Apache Arrow and can definitely generalize to 37 million datapoints. Otherwise, you can create your own dataset class and implement it as you like. There is no requirement to store 37 million `OrderedDict` objects in memory, only that you convert each row to an `OrderedDict` when it is used for the attack (returned by your dataset `__getitem__`).

**Comment by jxmorris12** [comment]
By the way, what is the reason you would ever want to generate 37 million adversarial examples from the same model?
