### ISSUE TITLE
Bug on CLARE when applying InputColumnModification constraint

### ISSUE THREAD

**Issue by JFChi** [QData/TextAttack#620]
**Describe the bug**
Hi I am trying to run CLARE on MNLI dataset. I tried to apply the InputColumnModification(["premise", "hypothesis"], {"premise"}) constraint to CLARE and found the constraint does not work: it still change the premise. For example, 

```
Neutral (100%) --> Contradiction (97%)
Premise: um-hum don't buy them that way uh-huh okay well i'll remember that
Hypothesis: Buy them that way, that's right.

Premise: um-hum Buy them that way uh-huh okay well i'll remember that
Hypothesis: Buy them that way, that's right.
```
**To Reproduce**
In the clare_li_2020.py, I add 
```
        input_column_modification = InputColumnModification(
            ["premise", "hypothesis"], {"premise"}
        )
        constraints.append(input_column_modification)
```
right after
```
        constraints = [RepeatModification(), StopwordModification()]
```

**Expected behavior**
I expect the attack after adding the constraint will only modify hypothesis.

**Screenshots or Traceback**
see above.

**System Information (please complete the following information):**
I am using textattack 0.3.3

**Comment by Hanyu-Liu-123** [comment]
Hi @JFChi, thank you for bringing this up. We will look into this!

**Comment by JFChi** [comment]
@Hanyu-Liu-123 , Thanks for you reply! 

Do you have any updates on this? I found the newest version of textattack still has the problem.

**Comment by JFChi** [comment]
This is another example. @Hanyu-Liu-123 

```
Neutral (98%) --> Entailment (100%)

Premise: Will you ask Sir James if I can see him for a few minutes?
Hypothesis: I want to see James for a few hours.

Premise: Will you ask Sir James if I can see him for a while?
Hypothesis: I want to see James for a few hours.
```

**Comment by JFChi** [comment]
@Hanyu-Liu-123, 

just have some updates on my side. I found another problem that might be related to this issue: 

In MNLI training example 255115, the CLARE attack generate an attack result like this, which means it attacks the split token.

```
you still there Fernando sorry uh<SPLIT>I thought I lost you for a minute.

you still there Fernando sorry uh<SPLOTS IT>I thought I lost you for a minute.
```

**Comment by JFChi** [comment]
> @Hanyu-Liu-123,
> 
> just have some updates on my side. I found another problem that might be related to this issue:
> 
> In MNLI training example 255115, the CLARE attack generate an attack result like this, which means it attacks the split token.
> 
> ```
> you still there Fernando sorry uh<SPLIT>I thought I lost you for a minute.
> 
> you still there Fernando sorry uh<SPLOTS IT>I thought I lost you for a minute.
> ```

This is another bug, I will open a new issue for that.

**Comment by JFChi** [comment]
@Hanyu-Liu-123, I think I fix the issue. The issue is here: https://github.com/QData/TextAttack/blob/master/textattack/transformations/word_merges/word_merge_masked_lm.py#L165-L166
Just insert one line then fix the issue.
```
merge_indices = find_merge_index(token_tags)
merge_indices = [i for i in merge_indices if i in indices_to_modify]
merged_words = self._get_merged_words(current_text, merge_indices)
```
