### ISSUE TITLE
'shuffle' is not work for me

### ISSUE THREAD

**Issue by YiLiuHFUT** [QData/TextAttack#628]
I am using the IMDB dataset and when I specify to attack 1000 samples, it will only attack the first 1000 positive samples. Why do I specify to attack 25,000 samples, and in the case of default 'shuffle=True', it still attack the positive samples first, instead of scrambled samples to attack?

**Comment by jxmorris12** [comment]
@YiLiuHFUT do you mind posting an example in a colab notebook? It seems that shuffle in the `HuggingFaceDataset` object isn't working properly for you.

**Comment by jxmorris12** [comment]
@VijayKalmath confirmed for me that shuffle is working properly. Feel free to reopen with a reproducible error.
