### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by malimsse26** [QData/TextAttack#630]
!textattack train --model lstm --dataset rotten_tomatoes 

Successfully trained but when I run below command:

!textattack eval --num-examples 1000 --model ./outputs/2022-03-22-15-24-31-623306/best_model/ --dataset-from-huggingface rotten_tomatoes --dataset-split test

SyntaxError: invalid syntax

Please do let me know where I am making mistake. I want to use LSTM

**Comment by jxmorris12** [comment]
Sorry @malimsse26 - this is definitely an installation error, since our package wouldn't even build if we used invalid syntax. Can you provide more information? Are you using Python 3.9? Did you install from pypi or source? What operating system do you use?

**Comment by jxmorris12** [comment]
If you're still struggling from this, please try it in Colab and post a link to your notebook where I can reproduce the error.
