### ISSUE TITLE
query limit does not work in NLI task

### ISSUE THREAD

**Issue by JFChi** [QData/TextAttack#663]
**Describe the bug**

When I set query limit to 5000 and use textfooler/bae/clare to attack SNLI or MNLI, it seems to me that the query limit does not work at all.

**Screenshots or Traceback**
{"model_name_or_path": "textattack/bert-base-uncased-MNLI", "attack_random_seed": 765, "query_budget": 5000, "original_premise": "For example, service coordination is a popular remedy for limited funds.", "original_hypothesis": "There are no ways to overcome fund limitation.", "perturbed_premise": "For example, service coordination is a popular remedy for limited funds.", "perturbed_hypothesis": "there are no way to overcome funding limitation.", "num_queries": 25, "original_score": 0.04158782958984375, "perturbed_score": 0.1366790533065796, "original_output": 0, "perturbed_output": 0, "ground_truth_output": 0, "result_type": "Failed"}}

This is one attack example, we can see it fails, but the num_queries << query_budget.

**Comment by jxmorris12** [comment]
The query limit sets the **maximum** number of queries. It seems this attack failed to find a valid adversarial example in just 25 queries, and then the search stopped. 

Which search method was used here? The premise is quite short, and only contains maybe 7 non-stopwords so it's not surprising to me that only 25 queries were used.

The query budget only kicks in if the search is trying to use more than X queries (in your case, X=5000). So here it seems to be working as intended.
