### ISSUE TITLE
subprocess-exited-with-error

### ISSUE THREAD

**Issue by inura-katulanda** [QData/TextAttack#685]
I tried to install this tool in my kali VM. 

Commands Used - pip install textattack

But following issue occurred.

![image](https://user-images.githubusercontent.com/78894960/183882900-239accb6-b04c-43e5-8bc4-6d5c92d46a5c.png)

**Comment by Kravrolens** [comment]
I had the same problem.

**Comment by slowpokeeh** [comment]
Solved by doing the following:
`sudo apt update`
`sudo apt upgrade`
`sudo apt install cmake`
`sudo apt install pkg-config`

**Comment by jxmorris12** [comment]
seems like a versioning issue with setuptools. Please follow these instructions: https://stackoverflow.com/questions/14426491/python-3-importerror-no-module-named-setuptools
