### ISSUE TITLE
The attacked_text is recursively called with no stop when using TextBugger attack.

### ISSUE THREAD

**Issue by plasmashen** [QData/TextAttack#690]
**Describe the bug**
The attacked_text is recursively called with no stop when using TextBugger attack.

**To Reproduce**
It seems that word_swap_embedding.py cause this problem.

**Screenshots or Traceback**
![image](https://user-images.githubusercontent.com/40386089/187620683-5abe6eba-e443-48c4-a9b6-c9218f54e3e6.png)

**System Information (please complete the following information):**
 - OS: Linux
 - Library versions (e.g. `torch==1.7.1, transformers==4.21.2`)
 - Textattack version 0.3.5

**Comment by jxmorris12** [comment]
@plasmashen - are you sure about the recursion? I think this might just mean you pressed ctrl-C while the above function was running.

that said, I think this function actually is pretty slow and could be optimized to just compare attackedtext by string representation. I don't see a use case where two AttackedText could have the same text but different attributes and shouldn't be considered equal.

**Comment by plasmashen** [comment]
I am sure about the recursion. As you can see from the interruption traceback, the __eq__ function is repeated 28 times which results in exponentially increasing in run-time. 

Since I have modified the code (which is provided in #691 ), the problem is fixed.

**Comment by jxmorris12** [comment]
thank you @plasmashen  :)

**Comment by jxmorris12** [comment]
merged!
