### ISSUE TITLE
Attacking T5 model doesn't work

### ISSUE THREAD

**Issue by poojithat512** [QData/TextAttack#697]
<img width="1075" alt="Screen Shot 2022-10-25 at 8 20 08 AM" src="https://user-images.githubusercontent.com/90569109/197785272-cde74e2f-a3fc-4753-b71a-a4443c8f220c.png">

**Comment by jxmorris12** [comment]
Hopefully I fixed this today with #700 :) can you try and pull the current code and let me know if your issue is fixed?

**Comment by jxmorris12** [comment]
Pretty sure this was fixed a few days ago! Please reopen if you're still having issues
