### ISSUE TITLE
Typo in Help String

### ISSUE THREAD

**Issue by JosephTLucas** [QData/TextAttack#702]
**Describe the bug**
[A clear and concise description of what the bug is.]
`texattack` should be `textattack` (missing second t in "text")
(https://github.com/QData/TextAttack/blob/49c94fb59bc60cae9e5e39d1a8a78f932a9fe9ed/textattack/commands/textattack_cli.py#L25)

**Comment by jxmorris12** [comment]
Thanks @JosephTLucas! Not gonna check the git blame for this one 😅 Fixed in #703
