### ISSUE TITLE
Support for token classification

### ISSUE THREAD

**Issue by vanboefer** [QData/TextAttack#704]
Hi! 
I would like to use TextAttack on a token-classification (NER) model. My dataset looks like this:
`[(['My', 'name', 'is', 'Bert', '.'], [0, 0, 0, 1, 0]), ...]`
When I'm trying to load the dataset I get:
`ValueError: Mismatch between the number of columns in input_columns and number of columns of actual input.`
Does TextAttack support token-classification models and datasets?
Thank you!

**Comment by jxmorris12** [comment]
Hi @vanboefer! So basically this is a new output format that's not supported by any of the textattack goal functions. We really only have goal functions for sequence outputs and classification outputs. 

Basically this is an open research problem. You'd have to think about what you want the goal of the attack to be, i.e. do you want to flip the NER prediction of specific tokens? Or a certain number of tokens, but you don't care which ones? Or to change the average probability by a certain amount in total? Let me know and I can help you design a new goal function to integrate with TextAttack if you want.

**Comment by jxmorris12** [comment]
Awesome! Thanks for letting me know about SeqAttack, looks perfect for your use case.
