### ISSUE TITLE
Question: Installing TextAttack with Specific TensorFlow version

### ISSUE THREAD

**Issue by SantoshYadaw** [QData/TextAttack#705]
Hi, is there a way to install TextAttack with a specific Tensorflow version? Thank you in advance

**Comment by jxmorris12** [comment]
Well, it is a Python package, so after installing TextAttack you can upgrade or downgrade TensorFlow to your version of choice!

**Comment by SantoshYadaw** [comment]
Ok noted with thanks @jxmorris12 :D
