### ISSUE TITLE
Error encountering while following tutorial

### ISSUE THREAD

**Issue by sh0416** [QData/TextAttack#716]
**Describe the bug**
Error encountering while following tutorial.
Link: https://textattack.readthedocs.io/en/latest/0_get_started/command_line_usage.html#data-augmentation-with-textattack-augment

**To Reproduce**

```
textattack augment \
     --input-csv resources/datasets-csv/sst2-openai/train.csv \
     --output-csv outputs.csv \
     --input-column sentence \
     --recipe eda \
     --pct-words-to-swap 0.1 \
     --transformations-per-example 2 \
     --exclude-original
```

**Expected behavior**
No error

**Screenshots or Traceback**

```
Traceback (most recent call last):
  File "/home/seonghyeon_scatterlab_co_kr/anaconda3/envs/research/bin/textattack", line 8, in <module>
    sys.exit(main())
  File "/home/seonghyeon_scatterlab_co_kr/anaconda3/envs/research/lib/python3.8/site-packages/textattack/commands/textattack_cli.py", line 50, in main
    func.run(args)
  File "/home/seonghyeon_scatterlab_co_kr/anaconda3/envs/research/lib/python3.8/site-packages/textattack/commands/augment_command.py", line 183, in run
    augmenter = eval(AUGMENTATION_RECIPE_NAMES[args.recipe])(
TypeError: __init__() got an unexpected keyword argument 'high_yield'
```

**System Information (please complete the following information):**
 - OS: Linux
 - Library versions: torch==1.12.0+cu113, transformers==4.26.1
 - Textattack version: 0.3.8

**Additional context**

**Comment by Minimindy** [comment]
Hi, do you find the solution in this problem?
I was in the same issue and end up comment out those two argument 'high_yield' and 'fast_augment' to make it work,
but I don't know if I was ok to do that,
thx.

**Comment by sh0416** [comment]
I just closed this issue because no one responds. I couldn't figure out the solution.
