### ISSUE TITLE
Potential bug of textattack.datasets.dataset.Dataset after calling filter_by_labels_

### ISSUE THREAD

**Issue by wenh06** [QData/TextAttack#745]
**Describe the bug**
After calling `filter_by_labels_`, the `_dataset` attribute of a `textattack.datasets.dataset.Dataset` instance is no longer a `list` but a `filter`, which has no `__len__` method, hence calling the `__len__` method of `textattack.datasets.dataset.Dataset` would result in `TypeError`.

**To Reproduce**

```python
import textattack
ds = textattack.datasets.dataset.Dataset(
    dataset=[
        ("Not good not bad.", 2),
        ("It is funny.", 1),
        ("Not interesting at all!", 0),
    ],
)
len(ds)  # 3
ds.filter_by_labels_(labels_to_keep=[0, 1])
len(ds)  # TypeError
```

**Expected behavior**

`len` method raises no error.

**Screenshots or Traceback**

![image](https://github.com/QData/TextAttack/assets/8778305/fc90ec41-dad0-455c-8eb8-e5220e8a94e5)

**System Information (please complete the following information):**
 - OS: Linux
 - Textattack: master

**Additional context**
NA

**Comment by jxmorris12** [comment]
this was fixed in #746 :)
